### ISSUE TITLE
run-initdb doesn't export env vars

### ISSUE THREAD

**Issue by dsmiley** [docker-solr/docker-solr#103]
I have a script I added to /docker-entrypoint-initdb.d/ that sets the SOLR_HOST variable conditionally based on some factors.  I discovered that setting any env vars here has no effect, contrary to the documentation in run-initdb which claims scripts can be added for this purpose.  I'm not a bash expert but it would appear that that there is some sort of sub-shell going on as part of the loop per init script such that any env var set within this loop doesn't survive.  I validated this theory by setting a bunch of env vars in various places in this file and checking at what point it vanishes.

**Comment by dsmiley** [comment]
Relevant: http://mywiki.wooledge.org/BashFAQ/024

**Comment by makuk66** [comment]
Thanks David, for the clear bug report and a link to a fix :-) https://github.com/docker-solr/docker-solr/commit/20e09a91045415c324bb6575bd63191624fa3875 fixes that. Can you test it out?

**Comment by dsmiley** [comment]
This works; thanks!
