### ISSUE TITLE
We should have an introduction video

### ISSUE THREAD

**Issue by makuk66** [docker-solr/docker-solr#104]
We should have an introduction video

**Comment by makuk66** [comment]
https://www.youtube.com/edit?o=U&video_id=Zqst7CwAT60

**Comment by dsmiley** [comment]
uh; that link doesn't work for me.  I suspect it's tied to _your_ account but I could be wrong.  Try getting a permalink / link share feature rather than just grabbing your browser's URL.

**Comment by makuk66** [comment]
Try that one https://www.youtube.com/watch?v=Zqst7CwAT60

**Comment by dsmiley** [comment]
That works.  Presumably you're going to link to this from the README?
