### ISSUE TITLE
init solr home script fails on filesystem roots

### ISSUE THREAD

**Issue by semkath** [docker-solr/docker-solr#107]
When trying to use the INIT_SOLR_HOME functionality, I noticed that the docker-solr/scripts/init-solr-home script checks if the directory is empty. It does so with this code

```
# don't do anything if it is non-empty
if [ $(find "$SOLR_HOME" -mindepth  1 | wc -l) != '0' ]; then
    exit
fi
```

This causes problems when $SOLR_HOME is at the root of a file system (for example in my case, a RAID disk array). It exits from the script, the $SOLR_HOME doesn't get setup correctly and the whole startup process fails.
This is because even on an otherwise completely empty filesystem, there is still one directory that gets created in all cases: lost+found. Since the check in the init solr home script doesn't account for this, the whole process breaks.

**Comment by semkath** [comment]
There is an obvious workaround for this: Just create a separate directory to hold $SOLR_HOME, somethink like $FS_ROOT/solr_home.

**Comment by makuk66** [comment]
Heh. I personally wouldn't want to mix the SOLR_HOME directory with anything else (what if a future sysadmin wants to remove it all, and doesn't spot the `lost+found`. What about different permissions causing warnings when you run `find`, what if you later want to backup the solr directory and now have to exclude the `lost+found`); I'd much prefer the separate directory as in your workaround.

There are two motivations behind that check: so we can skip the init when it has been done already, and so we reduce the likelihood of a misconfiguration spreading the solr contents all over some wrong directory like `/`. The former we could fix by looking for something solr-specific like `server/solr`. But I think the second motivation is a good one, and I don't really want to start special-casing things like `lost+found`.

**Comment by dsmiley** [comment]
+1 to @makuk66 statements

**Comment by semkath** [comment]
Thanks for the explanation :) I think the reasoning behind the code is fine, it just came as a surprise to me today. The problem was mainly that it just failed to create the container with a error message along the lines of "solr.xml was not found". Maybe there should be a small explanation when the init solr home script is exiting prematurely? A message like "SOLR_HOME is not empty. Exiting." would maybe help avoid this case in the future.
I agree with the explanation that SOLR_HOME should be empty, I just didn't consider the `lost+found` case and was left to wonder why it worked with one directory but (seemingly random) not with the other (the FS root).

**Comment by makuk66** [comment]
That's a fair comment. We can add a more specific check-for-existing and exit 0, then do the empty check, with a specific error, and exit 1.
