### ISSUE TITLE
While creating container, solr user is added to group nobody instead of group solr

### ISSUE THREAD

**Issue by mugdho** [docker-solr/docker-solr#116]
To create the solr user the command below is run
```docker
RUN adduser -S -u $SOLR_UID -g $SOLR_USER $SOLR_USER
```
However the option -g adds the GECOS field instead of adding user `solr` to group `solr`. Could we have the solr user added to group solr as well using the `-G` option?

**Comment by makuk66** [comment]
Nice find, that was the intention behind the `-g`.
