### ISSUE TITLE
Missing ps in latest?

### ISSUE THREAD

**Issue by ksclarke** [docker-solr/docker-solr#122]
I may be missing something, but the latest images seem to be missing `ps` which is a problem when running create_core with: `docker exec -it --user=solr my_solr bin/solr create_core -c my_core` When I run that I get: `bin/solr: line 714: ps: command not found`

When I run the create_core using the alpine image it finds the `ps` and is able to create the core. I bash'ed into the latest image and didn't see a `ps` in /bin (like I do with the alpine image).

**Comment by damienstanton** [comment]
Also getting this error on `latest`.

**Comment by damienstanton** [comment]
I believe I have located a spot in [the local image history](https://github.com/docker-library/repo-info/commit/927aef2b825775414e8e3047207454f78cb5980a#diff-117b86606a60649457421ca107fe7facL3237) showing where `procps` got removed as of `6.5.1`. Note that the diff is pretty large so takes a few seconds to load.

**Comment by david2202** [comment]
It's gone from 6.4.2 as well.

**Comment by paullinney** [comment]
It disappeared from 6.3 and just tried 6.6 and its missing too.

A couple of commands to re-install 
```
        docker exec -u root -i -t SolrSearch apt-get update -y
        docker exec -u root -i -t SolrSearch apt-get install -y procps
```

**Comment by makuk66** [comment]
> Is that normal that historic images can change without notice?

Docker can re-generate images; I guess the idea is that this way you can pick up fixes in the base images; but it does mean stuff can break, like in this case. I found https://github.com/debuerreotype/docker-debian-artifacts/issues/5:

> procps package ... was only included in jessie's minbase set by accident as a dependency of something else

We'l have to add it explicitly.

**Comment by makuk66** [comment]
```
$ docker pull solr:latest && docker run solr:latest ps 
latest: Pulling from library/solr
Digest: sha256:31497fd735d70045f1759515ac7fda8f0bd0f4aa311ca48fc9fd3f8654763922
Status: Image is up to date for solr:latest
  PID TTY          TIME CMD
    1 ?        00:00:00 ps
```
