### ISSUE TITLE
solr container connecting to apache cassandra container 

### ISSUE THREAD

**Issue by phanirajl** [docker-solr/docker-solr#127]
Please provide config details for solr container connecting to apache cassandra container

**Comment by makuk66** [comment]
I'm not even sure what you're asking for (index content from Cassandra? store indices in Cassandra?), but I don't have any specific Cassandra examples. We cannot provide config details for every possible third-party integration; ultimately this image is just Solr, so you should be able to treat it as such and do the integration yourself. I know that DataStax have some Cassandra/Solr integration and do Docker images, so perhaps they can help you.
