### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [docker-solr/docker-solr#128]
I want to build this image on arm64 architecture,but I'm not sure that can be support arm64 architecture https://archive.apache.org/dist/lucene/solr/6.6.0/solr-6.6.0.tgz

**Comment by makuk66** [comment]
Solr just requires Java. And docker-solr uses shell scripts, expecting bash and so on. So if you find yourself a debian+openjdk or apline+openjdk image for arm, modify the FROM line in the docker-solr Dockerfiles to that, and build, it might just work. I don't have an arm64 machine up at the moment, so I can't try it out.
Even if this works fine, it would be tricky to get to build on our Travis build infrastructure or the docker-library infrastructure, so it's probably not something we'd be able to incorporate into this repo.

**Comment by longquan7** [comment]
@makuk66 OK,thanks

**Comment by makuk66** [comment]
I created an arm64 node on [Scaleway](https://www.scaleway.com), based on their docker image.

Uname reports it as: 

```
Linux scw-c77bff 4.9.32 #1 SMP Wed Jun 14 18:37:07 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
```

I found an arm openjdk image for arm64 on [Docker hub](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=openjdk-arm&starCount=0).

```
$ docker pull arm64v8/openjdk

$ docker run arm64v8/openjdk java -version
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)

$ git clone https://github.com/docker-solr/docker-solr.git

$ cd docker-solr/6.6
$ sed -i 's,FROM .*,FROM arm64v8/openjdk,' Dockerfile
$ docker build -t solr-arm .
$ docker run -p 8983:8983 solr-arm solr-demo
```

That ran into some key fetching timeouts, but eventually built, and the demo runs fine. Neat.

Note: this exposes Solr on the public internet without protection; so firewall/proxy as appropriate.

**Comment by longquan7** [comment]
@makuk66 That' great, So Solr whether or not support arm64 architecture, can we push it to the https://hub.docker.com/u/arm64v8/  ?

**Comment by makuk66** [comment]
On a scaleway `ARM64-8GB`:

```
root@scw-f93731:~# docker run -it arm64v8/solr:6.6.1 dpkg --print-architecture
arm64

root@scw-f93731:~# docker run -it arm64v8/solr
Unable to find image 'arm64v8/solr:latest' locally
latest: Pulling from arm64v8/solr
Digest: sha256:8666805f40a3398d1a44a65e8bfa375fad330aa7838ce0bfe205edb91ad7ef23
Status: Downloaded newer image for arm64v8/solr:latest
Starting Solr 6.6.1
```

Even better, you don't need `arm64v8`:

```
root@scw-f93731:~# docker run -it solr dpkg --print-architecture
arm64

root@scw-f93731:~# docker run -it solr
Starting Solr 6.6.1
```

**Comment by hungvietdo** [comment]
> I created an arm64 node on [Scaleway](https://www.scaleway.com), based on their docker image.
> 
> Uname reports it as:
> 
> ```
> Linux scw-c77bff 4.9.32 #1 SMP Wed Jun 14 18:37:07 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
> ```
> 
> I found an arm openjdk image for arm64 on [Docker hub](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=openjdk-arm&starCount=0).
> 
> ```
> $ docker pull arm64v8/openjdk
> 
> $ docker run arm64v8/openjdk java -version
> openjdk version "1.8.0_141"
> OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
> OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)
> 
> $ git clone https://github.com/docker-solr/docker-solr.git
> 
> $ cd docker-solr/6.6
> $ sed -i 's,FROM .*,FROM arm64v8/openjdk,' Dockerfile
> $ docker build -t solr-arm .
> $ docker run -p 8983:8983 solr-arm solr-demo
> ```
> 
> That ran into some key fetching timeouts, but eventually built, and the demo runs fine. Neat.
> 
> Note: this exposes Solr on the public internet without protection; so firewall/proxy as appropriate.

This method works for me. It took 15 minutes to build solr 6.6 successfully on my Macbook chip M1/arm64v8
