### ISSUE TITLE
Docker Container prevents hibernation of hard drives

### ISSUE THREAD

**Issue by black-snake** [docker-solr/docker-solr#135]
Hey there,
first of all, great job you have done on containerizing Apache Solr!

I use a container of it for my Nextcloud full-text index functionality (in conjunction with Nextant). The index is being updated every 60 minutes (triggered from my Nextcloud container via cron). Sadly, I experience that the host's hard drives do not go into hibernation mode any longer as soon as I run an Apache Solr container.

This even happens if the Apache Solr container is not triggerd to do something from the outside (i. e. Nextcloud container is not running).

So, is there any configuration or tweak I can use so that the hard drives of the host system hibernate when there is actually nothing to do for Apache Solr? I already tried the 'normal' and the 'alpine linux' version of Apache Solr container which, however, proved to have no success / make any difference.

**information on my system and setup**
- Synology DS716+ (DSM 6.1) running latest Docker version that is officially available via Synology (Docker version 1.11.2, build 5be46ee-synology)
- Nextcloud container from https://github.com/Wonderfall/dockerfiles/tree/master/nextcloud
- Nextant v1.0.8 (latest)

(_last two bullet points are more fyi because the problem already occurs when Nextcloud is not running_)

Thank you so much in advance for any tips or solutions.

**Comment by makuk66** [comment]
You weren't using something that talks to Solr, like some background tab or some such?
Have you tried reproducing with Solr outside Docker, or some non-Solr Docker image?

I imagine either Solr is doing things in the background as part of normal operations, or Docker is. Docker-solr as such itself is not doing anything, so it's probably not something we can do much about.

I had a look with sysdig, and while I saw docker talk to the dockerd socket quite a bit, the Solr container itself didn't seem to do anything in steady state in the few minutes I was looking.

**Comment by black-snake** [comment]
Hey, thanks for that quick reply.

No, I wasn't using anything that talked to Solr. I have not tried to reproduce the issue with a normal (non-dockerized) Solr setup because (also because I'm not sure if I can install it my Synology NAS straight forward). But what do you mean by 'background tab'?

However, I know that the hard drives can go into hibernation mode with other Docker containers running. For example, if I just run the Nextcloud and MariaDB container (needed as DB for Nextcloud), the hard drives go into hibernation mode.

**Comment by makuk66** [comment]
> But what do you mean by 'background tab'?

Some web UIs auto-refresh or talk regularly to their server, so if you have a forgotten tab open with that UI, you might be generating traffic without realising that you are. I'm not sure if that applies to the Solr UIs, or your situation, but may be worth excluding as a possible cause.

If you look at the Solr logs, do you see anything happening there?

Try the steps in https://forum.synology.com/enu/viewtopic.php?f=83&t=13722&sid=faa0f283c051c3e95fd8bb22cfce0a03, in particular the `syno_hibernate_debug_tool`, and see if there is anything of interest in the `/var/log/messages`.

**Comment by black-snake** [comment]
Hey, thanks for the help so far.

I did not have any background tab running as the machine accessing the Solr UI and even the Nextcloud container communicating with Solr were switched off.

I had a look a the server logs of Solr and there is just the information that I can see on the stdout from the docker container. In the concrete case I was looking into, the Solr container started and around 10 seconds later there was the last log message:
`2017-09-04 17:20:34.040 INFO  (searcherExecutor-7-thread-1-processing x:nextant) [   x:nextant] o.a.s.c.SolrCore [nextant] Registered new searcher Searcher@1f401813[nextant] main{ExitableDirectoryReader(UninvertingDirectoryReader(Uninverting(_2(6.6.0):C8)))}`

The Synology hibernation debug tool didn't prove to be of any help or I was too dumb to use it (btw the name of the tool has apparently changed to 'syno_hibernation_debug' - just in case someone else wants has the same problem). The log output in the respective time is not very much (see below). The Solr container was started at 2017-09-04 17:20:25.434+02:00 and the NAS was untouched until 2017-09-04T18:53:05+02:00. Seems as if there a log entries for 'deepsleep' but there are generally no log entries for hibernation in this log file since no hdd hibernation is indicated by a log entry, even at times when there definitely was one (I can see that in another log from the Synology UI).

2017-09-04T17:14:56+02:00 NAS kernel: [1293833.932186] ata1: wake up from deepsleep, reset link now
2017-09-04T17:14:56+02:00 NAS kernel: [1293834.226871] ata1: device plugged sstatus 0x133
2017-09-04T17:15:03+02:00 NAS kernel: [1293840.931480] ata2: wake up from deepsleep, reset link now
2017-09-04T17:15:14+02:00 NAS kernel: [1293841.186092] ata2: device plugged sstatus 0x133
2017-09-04T17:15:14+02:00 NAS kernel: [1293842.721442] ata1: link is slow to respond, please be patient (ready=0)
2017-09-04T17:15:14+02:00 NAS kernel: [1293844.425593] ata1: wake up successful, the reset fail can be ignored
2017-09-04T17:15:14+02:00 NAS kernel: [1293849.720330] ata2: link is slow to respond, please be patient (ready=0)
2017-09-04T17:15:14+02:00 NAS kernel: [1293851.203171] ata2: wake up successful, the reset fail can be ignored
2017-09-04T17:52:19+02:00 NAS ddnsd: ddnsd.c:2931 DDNS Expired. UpdateAll.
2017-09-04T17:52:22+02:00 NAS ddnsd: ddnsd.c:1898 Success to update [] with IP [] at []
2017-09-04T18:53:05+02:00 NAS kernel: [1299723.075790] ata1: wake up from deepsleep, reset link now
2017-09-04T18:53:06+02:00 NAS kernel: [1299723.371607] ata1: device plugged sstatus 0x133
2017-09-04T18:53:12+02:00 NAS kernel: [1299730.075374] ata2: wake up from deepsleep, reset link now
2017-09-04T18:53:13+02:00 NAS kernel: [1299730.330413] ata2: device plugged sstatus 0x133
2017-09-04T18:53:14+02:00 NAS kernel: [1299731.866380] ata1: link is slow to respond, please be patient (ready=0)
2017-09-04T18:53:16+02:00 NAS kernel: [1299733.373341] ata1: wake up successful, the reset fail can be ignored
2017-09-04T18:53:21+02:00 NAS kernel: [1299738.869238] ata2: link is slow to respond, please be patient (ready=0)
2017-09-04T18:53:23+02:00 NAS kernel: [1299740.347029] ata2: wake up successful, the reset fail can be ignored

**Comment by makuk66** [comment]
The "new searcher" is probably a delayed commit See https://cwiki.apache.org/confluence/display/solr/UpdateHandlers+in+SolrConfig.
You may be able to configure that to come quicker, or do an explicit commit from your app.

I configured debug logging, and saw regular solr-idle-connections-evictor and Jetty's HashSessionManager activity. And I imagine there is some stats maintenance too. But those should not affect disk.

I did another sysdig, for longer, and noticed some `libjvm.so` seek/read traffic ~10min after the last activity, and then not again; I don't know what caused that.
I also noticed entries written to the gc log, 1h13 later. You could try disabled the gc log and see if that helps.
But both those sound infrequent enough that it should not prevent your hibernation.

**Comment by black-snake** [comment]
Hey,

I'm not exactly sure which commit method Nextant uses but even if it doesn't run, the hdd hibernation fails. So this can't be the root of the problem (at the moment). In addition, I'm not really experience enough to modify the code of Nextant as to make it's commits' explicit.

Regarding `libjvm.so` I can't really tell much because my expertise is somewhat limited on Linux-based machines and Solr in particular. However, you say that `libjvm.so` is just doing something once (after 10 minutes). So can't really be it, either.

Concerning the gc log I found in the configuration that it is turned off by default. I left this setting as is.

So, I'm clueless now. I think I will have to live with this issue. Too bad but thank you so much for your effort!
