### ISSUE TITLE
Create multiple collections at startup

### ISSUE THREAD

**Issue by makuk66** [docker-solr/docker-solr#142]
Solr-precreate creates a single core and then starts Solr.
It would be good to be able to create multiple cores without too much effort.

See https://github.com/docker-solr/docker-solr/pull/141#issuecomment-329230153

**Comment by makuk66** [comment]
This now works:
```
docker run -it -p 8983:8983 solr:7.0.0 bash -e -c "precreate-core core1; precreate-core core2; solr-foreground"
```

**Comment by jmanuelortiz** [comment]
Hi

Is this possible through docker-compose

Regards

Manuel

**Comment by cbernaut** [comment]
> Hi
> 
> Is this possible through docker-compose
> 
> Regards
> 
> Manuel

Yes, see solution here: https://github.com/docker-solr/docker-solr/issues/188
