### ISSUE TITLE
Missing DIH

### ISSUE THREAD

**Issue by AntonioCS** [docker-solr/docker-solr#145]
Hey,

I am new to solr and I am running version 6.
I have created a core (using the cli command) but that core doesn't have any DataImportHandler.

I am trying to figure out how to import data from a postgres database and some tutorials say that I should have DIH in the admin core section.

Is this something that is missing from the image or do I need to add it manual (if so how?)

Thanks!

**Comment by makuk66** [comment]
docker-solr is a standard Solr distribrution, without docs, and with some added scripts. So yes, DIH is included. Observe:
```
$ docker create --name tmp1 solr:latest
3083d5cf4e804260a47b3ed4ee440b6f6544205213556f45acdfbaf65f59af7b

$ docker cp tmp1:/opt/solr tmp1-solr

$ docker rm tmp1
tmp1

$ find tmp1-solr -name '*.jar' -exec bash -c "jar tf {} | grep -q DataImportHandler && echo {}" \;
tmp1-solr/dist/solr-dataimporthandler-6.6.0.jar
```

The jars in `dist` are not loaded by default; you'll need to modify the `solrconfig.xml` to load it.


For example, inspired by [DIHQuickStart](https://wiki.apache.org/solr/DIHQuickStart):

Grab the solrconfig from the container:

```
docker create --name tmp1 solr:latest
docker cp tmp1:/opt/solr/server/solr/configsets/data_driven_schema_configs/conf/solrconfig.xml solrconfig.xml
docker rm tmp1
```

Modify it to load the dataimporthandler, and add a requesthandler configuration for it:

```
ed solrconfig.xml <<'EOM'
$
?requestHandler>
a
<requestHandler name="/dataimport" class="org.apache.solr.handler.dataimport.DataImportHandler">
<lst name="defaults">
  <str name="config">data-config.xml</str>
</lst>
</requestHandler>
.

1
/regex="solr-velocity-
a
  <lib dir="${solr.install.dir:../../../..}/dist/" regex="solr-dataimporthandler-\d.*\.jar" />
.
w
q
EOM
```

Create the referenced config file:

```
cat > data-config.xml <<EOM
<dataConfig>
  <dataSource type="JdbcDataSource" 
              driver="com.mysql.jdbc.Driver"
              url="jdbc:mysql://localhost/dbname" 
              user="user-name" 
              password="password"/>
  <document>
    <entity name="id" 
            query="select id,name,desc from mytable">
    </entity>
  </document>
</dataConfig>
EOM
```

Mount both into your container:

```
docker run -it -p 8879:8983 \
  -v $PWD/solrconfig.xml:/opt/solr/server/solr/configsets/data_driven_schema_configs/conf/solrconfig.xml \
  -v $PWD/data-config.xml:/opt/solr/server/solr/configsets/data_driven_schema_configs/conf/data-config.xml \
  solr solr-precreate core1
```

Then go to http://localhost:8879/solr/#/core1/dataimport and observe the green "/dataimporthandler" (as opposed to red "Solr DataImportHandler not found" errors).

Hopefully that should get you going; let us know how you get on!

**Comment by dsmiley** [comment]
@makuk66 You always impress me with your detailed how-to responses and bash expertise!

**Comment by AntonioCS** [comment]
@makuk66 Thanks for such a great explanation. I will try this and let you know.

**Comment by AntonioCS** [comment]
@makuk66 Sorry for not saying anything. I was moved to a different project and haven't had the change to do anything on this. Thanks again for your time and effort on the explanation.
