### ISSUE TITLE
Data Import Handler (DIH) Persisting dataimport.properties

### ISSUE THREAD

**Issue by jamiejackson** [docker-solr/docker-solr#150]
`dataimport.properties` ought to live through server restarts, as its tied to index data.

Currently, every time the container is restarted/recreated, `dataimport.properties` gets "removed" since it's written on the container layer, inside of the core. Because of this, a "full" import is forced, which is inefficient (and doesn't make sense).

I think this (PropertyWriter solution) was an attempt to fix the issue, but I'm not sure it went far enough (or I'm not sure how to use it properly): https://issues.apache.org/jira/browse/SOLR-1970

We need:

* A workaround, or
* a recipe for using PropertyWriter (i.e., if it actually does what we need it to), or
* an upstream fix to get Solr to write to the data area, where this belongs, IMO. (Whereas I think the _core_ area should be thought of as read-only.)

I'm pursuing this here (in the Docker context), since Docker users will recognize the problem, whereas conventional Solr users won't care too much.

**Comment by makuk66** [comment]
One workaround is to use [init-solr-home](https://github.com/docker-solr/docker-solr/blob/master/scripts/init-solr-home#L8). Alternatively, mount a local file at that location. Or perhaps add a script to create a symlink to a file in your core.

For PropertyWriter I found docs on https://lucene.apache.org/solr/guide/6_6/uploading-structured-data-store-data-with-the-data-import-handler.html#property-writer and an example in the wild on https://stackoverflow.com/questions/21580331/solr-delta-import-not-working. Is that any help?

An upstream fix to use the core dir as the default sound like the best solution here.

**Comment by dsmiley** [comment]
> An upstream fix to use the core dir as the default sound like the best solution here.

+1

**Comment by jamiejackson** [comment]
> An upstream fix to use the core dir as the default sound like the best solution here.

You guys meant to say the _data_ dir, right? (If so, we're on the same page.)

Checking out your workarounds now, @makuk66 .

**Comment by jamiejackson** [comment]
# init-solr-home Workaround

I think I don't understand the details of this workaround

# PropertyWriter Workaround

> ... an example in the wild on https://stackoverflow.com/questions/21580331/solr-delta-import-not-working. Is that any help?

```xml
<propertyWriter ... directory="D:/tmp" filename="knowledgebase.dih.properties" ... />
```

That might help, since it shows an absolute path. I'd thought that wasn't possible for some reason.

Assuming absolute paths work, I could do something like this:

```xml
<propertyWriter
  directory="/opt/solr/data/${solr.core.name}"
  type="SimplePropertiesWriter" />
<!-- or -->
<propertyWriter
  directory="/opt/solr/data"
  filename="${solr.core.name}.dataimport.properties" 
  type="SimplePropertiesWriter" />
```

# Symlink Workaround

I guess I'd do something like this for each core

```
touch /opt/solr/data/core_a/dataimport.properties
ln -s /opt/solr/data/core_a/dataimport.properties /opt/solr/server/solr/mycores/core_a/conf/dataimport.properties
```

**Comment by jamiejackson** [comment]
I created an upstream ticket: https://issues.apache.org/jira/browse/SOLR-11402

**Comment by makuk66** [comment]
> I think I don't understand the details of [the init-solr-home] workaround

Well, you had the `dataimport.properties` in the `conf` directory in the solr home directory right?
So you could copy the whole solr home to a volume, and use that instead of the default solr home.
In docker-solr you can do that with a one-liner e.g. `docker run -it   -v $PWD/mysolrhome:/mysolrhome   -e SOLR_HOME=/mysolrhome   -e INIT_SOLR_HOME=yes solr solr-precreate mycore1`: docker-solr will see the `INIT_SOLR_HOME=yes`, copy the solr home into `$SOLR_HOME`, and then Solr will use that.
Or alternatively, you can do it by hand:
```
docker volume create solr_home
docker run -it -rm --user root -v solr_home:/mysolrhome solr bash -c "cp -a server/solr/*  /mysolrhome; chown -R 8983:8983 /mysolrhome"
docker run -it -v solr_home:/opt/solr/server/solr solr solr-precreate core1
```
Whether that is appealing depends a bit on how you use it.

**Comment by jamiejackson** [comment]
@makuk66, by default it's `/opt/solr/server/solr/mycores/{core_name}/conf/dataimport.properties`.

I think I get your workaround, thanks for the brainstorm. BTW, what's the `SOLR_HOME` when it's not explicitly specified? (I'm not sure which level of `/opt/solr/server/solr/mycores/` it is.)

For now, I think I'm going to try the following PropertyWriter. It feels like the most straightforward approach for now, and I'd guess the end result will be pretty similar to the way the upstream fix will work (if they move forward with it).
```xml
<propertyWriter
  directory="/opt/solr/data/${solr.core.name}"
  type="SimplePropertiesWriter" />
```
