### ISSUE TITLE
openjdk:9-jre and BYN Currency

### ISSUE THREAD

**Issue by grachevko** [docker-solr/docker-solr#154]
Solr images builds on top of openjdk:8-jre, but this jre don't have support for BYN currency.
Is there plans to update to openjdk:9-jre?

**Comment by makuk66** [comment]
Solr 7 is now tested with and verified to support Java 9, so we could.
We could either just switch Solr 7 to Java 9, or start down the road of producing `7.1.0-jdk-8`/`7.1.0-jdk-9` and so on (in their different slim/alpine flavours). I can imagine the latter might be useful in some cases. But this will require some build process changes and further investigation.

**Comment by grachevko** [comment]
To solve issue we had to use custom image, which build on top of openjdk:9-jre.
Is there reason to split images to different jre version?

**Comment by makuk66** [comment]
There could be incompatibilties, like https://issues.apache.org/jira/browse/SOLR-10199

**Comment by makuk66** [comment]
```
mak@cylon 2003 docker-solr [master] $ docker run -it --rm solr:7.3.0 java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-4)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-4, mixed mode)
```
