### ISSUE TITLE
What is the recommended way to mount a persistent volume in the SolrCloud mode?

### ISSUE THREAD

**Issue by stefan-langenmaier** [docker-solr/docker-solr#157]
Hi,

as far as I understand the documentation the `mycores` folder is there to use it as mount point for cores you want to persist outside of the docker container.

When I use the Solr cloud mode and want to create a collection while the server is running I cannot specify the instanceDir when creating a collection, so the created directory structure is always in `/opt/solr/server/solr`. When I directly mount this folder I'm shadowing important configuration files like solr.xml.

What am I missing? Is this possible?

**Comment by makuk66** [comment]
Right; it's a shame solr works that way, and there is upstream discussion on changes to make that easier. For now though you should be able to use the https://github.com/docker-solr/docker-solr#custom-solr_home mechanism

**Comment by stefan-langenmaier** [comment]
Thanks for your fast feedback. I'm sure I have read the README ten times, but looks like I didn't get it. Maybe it's already too late. :)
Thanks again, this should solve my problem!
