### ISSUE TITLE
Is teasseract build in in docker images of solr?

### ISSUE THREAD

**Issue by vistalba** [docker-solr/docker-solr#158]
Hi

I'm using solr as 6-alpine docker image.
Is teasseract build in? For me it look like solr only indexing pdfs which already has ocr content in the pdf file itself but not one that I have scanned by myself.

a) shoult OCR of PDF work out of the box?
b) is teasseract build in?

**Comment by makuk66** [comment]
No to both. The docker-solr image contains a standard Solr distribution, nothing more.
