### ISSUE TITLE
Docs for Kubernetes

### ISSUE THREAD

**Issue by makuk66** [docker-solr/docker-solr#164]
We should have an example of how to run Solr on kubernetes

**Comment by makuk66** [comment]
We need a helm chart. Discussion elsewhere:
https://github.com/kubernetes/charts/issues/3058
https://github.com/kubernetes/helm/issues/3265
https://github.com/guigo2k/helm-solr

**Comment by makuk66** [comment]
See https://lucidworks.com/2019/02/07/running-solr-on-kubernetes-part-1/

**Comment by sylus** [comment]
Hey @makuk66 is the lucidworks one kind of close to? https://github.com/helm/charts/issues/3058 only asking cause already using it and curious about the switch over since is working rather well.

**Comment by makuk66** [comment]
I haven't studied either in detail, so I can't say how they compare. I rather liked the blog post though, and know Lucidworks have a vested interest in their stuff. But if what you have works, why change.
You can track the progress of discussion/acceptance over on https://github.com/helm/charts/pulls?utf8=✓&q=is%3Apr+is%3Aopen+solr and I'm sure they'd welcome your insights.
