### ISSUE TITLE
SOLR_PORT check is missing on solr-precreate

### ISSUE THREAD

**Issue by Schnitzel** [docker-solr/docker-solr#165]
the introduced `SOLR_PORT` check here
https://github.com/docker-solr/docker-solr/blob/6d7fa219c3b3407e0dd29fb17b15ec9e6df85058/5.5/alpine/scripts/solr-create#L35-L38
is missing in the `solr-precreate` scripts:
https://github.com/docker-solr/docker-solr/blob/master/5.5/alpine/scripts/solr-precreate

this causes solr to start with weird ports like `SOLR_PORT=tcp://172.30.32.255:8983` when running in Kubernets and overwritten entrypoints

**Comment by makuk66** [comment]
That needs fixing. But, if the scenario where you are triggering that, adding that won't make it work, just exit.
Can you be more specific about "overwritten entrypoints" in your scenario; what are you doing and why?
It may be that to support your scenario we would have to make further changes.
In the meantime, does setting SOLR_PORT=8983 explicitly in your kubernetes deployment work around this?

**Comment by makuk66** [comment]
Original reported issue was fixed.
