### ISSUE TITLE
SolrСloud performance in Docker lower than one host machine installation

### ISSUE THREAD

**Issue by sunthera** [docker-solr/docker-solr#166]
My  previous SolrCloud one host-based installation is quicker than Docker-based SolrCloud. Performance decreased a lot.

Old setup:
VPS: 2 CPU 4gb RAM
Solr: 7.2, 4 nodes
OS: Ubuntu 16.04 LTS (server)

New setup:
VPS: 8 CPU 4gb RAM, (started with 2, added 6 additional)
OS: ubuntu 16.04 LTS (server)
Docker: 17.05.0-ce
Docker image: solr:7.2.1, 4 containers

schema, solrconfig unchanged.

With the old setup average response time is 100ms, now avg response time is 180ms. Adding 2 more cores increased performance, avg response time dropped to 130ms. Adding 4 more CPU cores (8 in total) had no any effect at all. 

Tried manually `cpuset` for each container - no results.
Also noticed in general (for old setup too) it is not a big difference between 2 and 4 Solr instances, but 

I'm wondering is this issue related to running JVM in containers or it is Solr Docker issue.
Has anyone noticed similar?

**Comment by makuk66** [comment]
I don't have any comparison data to offer.
Do your VPS have the same kind of disk?
Have you experimented with different Docker storage servers (check with `docker info`).
Are you using mounted host volumes, or any other volumes?
Have you looked at avg response time for non-queries?
Have you looked at other servers, like say Tomcat, on both?

**Comment by sunthera** [comment]
Yes, VPS are 1:1 clones. Both of them have SSD disks.
Docker Storage Driver: aufs, it's pretty default installation.
mounted volumes with local driver.
I think you mean something like network latency. It's not a case I guess.
No, not looked for others, both run on build-in jetty.

Perhaps you are right, something with storages / volumes
Thanks for input!

**Comment by sunthera** [comment]
Did not found root of the problem, but solved it in different way: created more shards, response time decreased significantly.
