### ISSUE TITLE
Variable undefined

### ISSUE THREAD

**Issue by rofc** [docker-solr/docker-solr#167]
$SOLRT_PORT should be replace with $SOLR_PORT in:

> 5.5/slim/scripts/solr-create:  echo "Invalid SOLR_PORT=$SOLRT_PORT environment variable specified"
> 5.5/scripts/solr-create:  echo "Invalid SOLR_PORT=$SOLRT_PORT environment variable specified"
> 5.5/alpine/scripts/solr-create:  echo "Invalid SOLR_PORT=$SOLRT_PORT environment variable specified"
> 6.6/slim/scripts/solr-create:  echo "Invalid SOLR_PORT=$SOLRT_PORT environment variable specified"
> 6.6/scripts/solr-create:  echo "Invalid SOLR_PORT=$SOLRT_PORT environment variable specified"
> 6.6/alpine/scripts/solr-create:  echo "Invalid SOLR_PORT=$SOLRT_PORT environment variable specified"
> 7.1/slim/scripts/solr-create:  echo "Invalid SOLR_PORT=$SOLRT_PORT environment variable specified"
> 7.1/scripts/solr-create:  echo "Invalid SOLR_PORT=$SOLRT_PORT environment variable specified"
> 7.1/alpine/scripts/solr-create:  echo "Invalid SOLR_PORT=$SOLRT_PORT environment variable specified"
> 7.2/slim/scripts/solr-create:  echo "Invalid SOLR_PORT=$SOLRT_PORT environment variable specified"
> 7.2/scripts/solr-create:  echo "Invalid SOLR_PORT=$SOLRT_PORT environment variable specified"
> 7.2/alpine/scripts/solr-create:  echo "Invalid SOLR_PORT=$SOLRT_PORT environment variable specified"
> scripts/solr-create:  echo "Invalid SOLR_PORT=$SOLRT_PORT environment variable specified"
>

**Comment by makuk66** [comment]
@rofc Thanks for the report!
