### ISSUE TITLE
Solr 6 - solr-precreate with custom config

### ISSUE THREAD

**Issue by aguilarm** [docker-solr/docker-solr#169]
Hi, I'm running Solr on kubernetes and when I use the command `["solr-precreate", "customcore", "/custom-config"]` solr errors out because it cannot find `elevate.xml` which I'm assuming it means it cannot find *any* config.

So, when running this command I end up with an error stack that starts with

```
java.util.concurrent.ExecutionException: org.apache.solr.common.SolrException: Unable to create core [customcore]
```
and ends at
```
Caused by: org.apache.solr.common.SolrException: QueryElevationComponent missing config file: 'elevate.xml
either: /opt/solr/server/solr/mycores/customcore/conf/elevate.xml or /opt/solr/server/solr/mycores/customcore/data/elevate.xml must exist, but not both.
```

My config is added to `/opt/solr/server/solr/mycores/customcore` rather than the `conf` subdirectory there.

Adding a symlink for conf pointing at the parent dir resolves the issue.

I am providing my configuration at `/custom-config` without a conf subdirectory, but interestingly adding a conf subdir does not fix this.

The `precreate-core` script looks like it would add conf if I added it but maybe I'm missing something?

Thanks

**Comment by makuk66** [comment]
The configsets in Solr are named directories containing a `conf` dir that has config files:

```
$ docker run -it solr bash
solr@5e0ca15fc61b:/opt/solr$ cd server/solr/configsets
solr@5e0ca15fc61b:/opt/solr/server/solr/configsets$ ls
_default  sample_techproducts_configs
solr@5e0ca15fc61b:/opt/solr/server/solr/configsets$ ls sample_techproducts_configs/
conf
```

and that's what `solr-precreate` expects.

> I am providing my configuration at /custom-config without a conf subdirectory, but interestingly adding a conf subdir does not fix this.

Works for me:

```
$ docker create --rm --name copier solr
8c99ea79c6623f40299068e16c5d2cff08fe0c4b80fb9a45b3cb9869980a9dc2
$ docker cp copier:/opt/solr/server/solr/configsets/sample_techproducts_configs myconfig
$ docker rm copier

$ docker run --name solr-customconfig -p 8983:8983 \
  -v $PWD/myconfig:/custom-config:ro \
  solr solr-precreate mycore /custom-config
Executing /opt/docker-solr/scripts/solr-precreate mycore /custom-config
Executing /opt/docker-solr/scripts/precreate-core mycore /custom-config
created mycore
2018-03-08 10:16:58.301 INFO  (main) [   ] o.e.j.s.Server jetty-9.3.20.v20170531

$ docker exec -it solr-customconfig bash -c "ls /custom-config"
conf
```

There's no reason things should be different on kubernetes, so I'm guessing you made a mistake somewhere. Did you verify that `/custom-config/conf/elevate.xml` exists in the container?

**Comment by aguilarm** [comment]
Sorry for letting this go stale but it everything does work correctly.  This was user error, failing to update tags properly on my end.  Thanks for looking though!

**Comment by makuk66** [comment]
Ah, glad to hear you got it straightened out! And thanks for taking the time to close this out.
