### ISSUE TITLE
Add Alpine variants

### ISSUE THREAD

**Issue by makuk66** [docker-solr/docker-solr#17]
It'd be nice to have Alpine variants.

See PR https://github.com/docker-solr/docker-solr/pull/16

**Comment by LaurentGoderre** [comment]
Can you let me know when the images are on the registry?

**Comment by makuk66** [comment]
This can get picked up with the upcoming Solr 6 release. RCs are currently being voted on, so I expect it won't be too long. I'll leave this bug open until it's done.

Thanks again for this contribution.

**Comment by LaurentGoderre** [comment]
Perfect!

**Comment by LaurentGoderre** [comment]
Version 6 is out, shouldn't it have been picked up?

**Comment by makuk66** [comment]
It's pending https://github.com/docker-library/official-images/pull/1637

**Comment by LaurentGoderre** [comment]
AAh! I didn't know how this process worked.

**Comment by makuk66** [comment]
@LaurentGoderre If you're curious, the process we follow for adding new versions is documented on https://github.com/docker-solr/docker-solr/blob/master/update.md . Submitting the PR for the official-image repository is the last step there.

In the meantime you can try our test builds:
```
mak@cylon:~/docker-solr$ docker run -it dockersolr/docker-solr:6.0-alpine bash
bash-4.3$ cat /etc/alpine-release 
3.3.3
bash-4.3$ grep '=====' /opt/solr/CHANGES.txt | head -n 1
==================  6.0.0 ==================
```
See https://github.com/docker-solr/docker-solr/issues/24#issuecomment-214246214 for how that is set up.

**Comment by LaurentGoderre** [comment]
aaaaah that's how you do it! Thank you!

**Comment by sylus** [comment]
It has now been merged! :)

**Comment by makuk66** [comment]
Yay!
