### ISSUE TITLE
Creating core at runtime 

### ISSUE THREAD

**Issue by Fatalityap** [docker-solr/docker-solr#172]
Hi how can I create cores at runtime (when container and solr is actually runing) ? 

I am writing a service that will create cores on a fly but API requests from some other services. I was trying to use this https://github.com/docker-solr/docker-solr/blob/master/README.md#creating-cores but I have no luck. 

Is this functionality present in you container or maybe you plan to add it in near future or maybe I am doing something wrong?

**Comment by makuk66** [comment]
You'll need to be more specific about what you're trying.

Doing:
```
docker run --name -p 8983:8983 my_solr solr:7.3
docker exec -it my_solr solr create_core -c mycorehere
```
works just fine.

If you want to have some API that does this, then you can create one using a separate container, pass in the docker socket, and call the exec from that.

Creating a core remotely directly with the Solr API is possible; there is an API https://lucene.apache.org/solr/guide/7_3/coreadmin-api.html#coreadmin-create, but that requires filesystem changes to be done prior. If you run in SolrCloud mode that's not required.
