### ISSUE TITLE
Setting up solr on a docker container to provide search service for drupal 8 (search_api_solr)

### ISSUE THREAD

**Issue by UltraBob** [docker-solr/docker-solr#174]
I've been trying different things for a few days now, and thought I'd ask here in hopes that someone can point me in the right direction.  I'm trying to set solr up to run in a docker container because we have an old solr 5.5 install that is running a live website, but a new website we are developing requires solr 6.  The drupal module that enables the integration provides a [config folder](https://cgit.drupalcode.org/search_api_solr/tree/solr-conf/6.x) which in my test environment is located at ```/path/modules/search_api_solr/solr-conf/6.x``` I've also created a mycores folder at ```/path/mycores```

I'm running the following command to try to get up and running with a new core in the mycores folder using the config from the drupal module:

`docker run -v /path/mycores:/opt/solr/server/solr/mycores -v /path/modules/search_api_solr/solr-conf/6.x/:/myconf -d --name solr_alpine_66 -p 8984:8983 -t solr:6.6-alpine solr-precreate drupalcore /myconf`

The container spins up and I see that a drupalcore directory is created in mycores.

When I look at the Solr Dashboard I see:

> SolrCore Initialization Failures
> drupalcore: org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Error initializing QueryElevationComponent.
> Please check your logs for more information

I look at the logs, and see a few warnings about deprecated plugins, then the following warning:

> 2018-05-28 09:23:24.930 WARN  (coreLoadExecutor-6-thread-1) [   x:drupalcore] o.a.s.r.ManagedResourceStorage Cannot write to config directory /opt/solr/server/solr/mycores/drupalcore/conf; switching to use InMemory storage instead.

After that I see two errors:

> 2018-05-28 09:23:25.312 ERROR (searcherExecutor-7-thread-1-processing-x:drupalcore) [   x:drupalcore] o.a.s.h.RequestHandlerBase java.lang.NullPointerException
at org.apache.solr.handler.component.SearchHandler.initComponents(SearchHandler.java:184)
at org.apache.solr.handler.component.SearchHandler.getComponents(SearchHandler.java:204)
at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:251)
at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:173)
at org.apache.solr.core.SolrCore.execute(SolrCore.java:2477)
at org.apache.solr.core.QuerySenderListener.newSearcher(QuerySenderListener.java:74)
at org.apache.solr.core.SolrCore.lambda$getSearcher$15(SolrCore.java:2249)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

and

> 2018-05-28 09:23:25.421 ERROR (coreContainerWorkExecutor-2-thread-1) [   ] o.a.s.c.CoreContainer Error waiting for SolrCore to be created
java.util.concurrent.ExecutionException: org.apache.solr.common.SolrException: Unable to create core [drupalcore]
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at org.apache.solr.core.CoreContainer.lambda$load$6(CoreContainer.java:594)
at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.common.SolrException: Unable to create core [drupalcore]
at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:966)
at org.apache.solr.core.CoreContainer.lambda$load$5(CoreContainer.java:565)
at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:197)
... 5 more
Caused by: org.apache.solr.common.SolrException: Error initializing QueryElevationComponent.
at org.apache.solr.core.SolrCore.<init>(SolrCore.java:977)
at org.apache.solr.core.SolrCore.<init>(SolrCore.java:830)
at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:950)
... 7 more
Caused by: org.apache.solr.common.SolrException: Error initializing QueryElevationComponent.
at org.apache.solr.handler.component.QueryElevationComponent.inform(QueryElevationComponent.java:255)
at org.apache.solr.core.SolrResourceLoader.inform(SolrResourceLoader.java:694)
at org.apache.solr.core.SolrCore.<init>(SolrCore.java:956)
... 9 more
Caused by: org.apache.solr.common.SolrException: QueryElevationComponent missing config file: 'elevate.xml
either: /opt/solr/server/solr/mycores/drupalcore/conf/elevate.xml or /opt/solr/server/solr/mycores/drupalcore/data/elevate.xml must exist, but not both.
at org.apache.solr.handler.component.QueryElevationComponent.inform(QueryElevationComponent.java:232)
... 11 more

It looks like it is complaining about elevate.xml existing in two places, but everything it is complaining about is in the mycores directory, and thus was created as part of the start up process.  How can I remedy this and get things going?

**Comment by makuk66** [comment]
```
2018-05-28 09:23:24.930 WARN (coreLoadExecutor-6-thread-1) [ x:drupalcore] o.a.s.r.ManagedResourceStorage Cannot write to config directory /opt/solr/server/solr/mycores/drupalcore/conf; switching to use InMemory storage instead.
```
That is because that directory does not exist. 

If you look at the included configs, they have a named directory, and a `conf` dir inside:
```
$ docker run -it solr:6.6 bash
solr@ba178fabb612:/$ ls /opt/solr/server/solr/configsets/basic_configs
conf
```
You want to replicate that:

```
git clone git@github.com:mkalkbrenner/search_api_solr.git
sudo rm -fr mycores/ myconf/
mkdir -p myconf mycores
cp -r $PWD/search_api_solr/solr-conf/6.x myconf/conf
sudo chown -R 8983:8983 myconf mycores

docker run \
 -v $PWD/mycores:/opt/solr/server/solr/mycores \
 -v "$PWD/myconf/:/myconf" \
 -p 8983:8983 -t solr:6.6 \
 solr-precreate drupalcore /myconf
```

**Comment by UltraBob** [comment]
That is what I was trying to configure with ```-v /path/modules/search_api_solr/solr-conf/6.x/:/myconf``` and ```/myconf``` at the end.  As far as I'm understanding from reading your response so far is that I needed the 6.x folder from search_api_solr to be in ```/myconf/conf``` instead of ```/myconf```.  Note, I ran a diff between the 6.x folder from the git clone operation and the one I'm using, and they are identical.  I tried mapping 6.x to /myconf/conf and got identical results.  the issue seems to be that it is trying to write the conf inside of the core.

so I changed my docker run command to mount 6.x in ```/opt/solr/server/solr/mycores/drupalcore/conf``` and while that gave me a bunch of warnings like 

> Couldn't add files from /opt/solr/server/solr/mycores/drupalcore/../../../dist filtered by solr-langid-\d.*\.jar to classpath: /opt/solr/server/solr/mycores/drupalcore/../../../dist

it does seem to have successfully created a core.  It appears that my mount point was bad and that /myconf at the end must just be being disregarded, or I'm misunderstanding what it is.  Thanks for the help.

**Comment by makuk66** [comment]
So you did:
```
sudo rm -fr mycores/
mkdir -p mycores
sudo chown -R 8983:8983 mycores
docker run  --rm -v $PWD/mycores:/opt/solr/server/solr/mycores  -v "$PWD/search_api_solr/solr-conf/6.x:/myconf/conf" -t solr:6.6  solr-precreate drupalcore /myconf
```
while your `solrconfig.xml` file has:
```
$ grep langid search_api_solr/solr-conf/6.x/solrconfig.xml|grep install
  <lib dir="${solr.install.dir:../../../..}/contrib/langid/lib/" regex=".*\.jar" />
  <lib dir="${solr.install.dir:../../../..}/dist/" regex="solr-langid-\d.*\.jar" />
```
and that conf dir has a `solrcore.properties` containing:
```
$ grep install search_api_solr/solr-conf/6.x/solrcore.properties
solr.install.dir=../../..
```
which works if the core is directly below `solr`, whereas we placed it in `solr/mycores`.
Just comment out that line in `solrcore.properties`, it gets set properly by Solr itself.

**Comment by UltraBob** [comment]
I did run what you mentioned except the chown command which I don't understand (my understanding of that command would be to make the folder owned by user with id 8983 and the group with id 8983) it all worked without that so I haven't run that command.

Anyway on to the meat of this this:

Hmm, ok, I see.  The thing is, that if I change that solrcore.properties file, it will be overwritten when I update the module.  I can make a copy of that folder and use that config, but then I lose any improvements that might be made in the module to the configuration, so I wonder, is there a way to get to install drupalcore directly under ```solr``` and precreate that drupalcore volume so I can mount it from a host directory?  I remember when I was experimenting with this earlier, if the core volume already existed but was empty, solr complained and failed to make the core.

**Comment by makuk66** [comment]
> I did run what you mentioned except the chown command which I don't understand (my understanding of that command would be to make the folder owned by user with id 8983 and the group with id 8983)

Correct. The solr image runs as the "solr" user, with the 8983 user id. So when using a host-mounted directory, doing the `chown` means the container can write to it.

> it all worked without that so I haven't run that command.

Are you OSX? I think things are slightly different there these days.

> I can make a copy of that folder and use that config, but then I lose any improvements that might be made in the module to the configuration

You mean when you `git pull` that `search_api_solr.git` repo? Right, but equally you should be vetting any such changes. I'd make a branch for your project, and then `git pull` on `master`, and merge into your branch, while vetting/modifying as required.
Also, note that the core creation copies the config into the core directory, so any changes in your repo will not be applied unless you re-create the core each time.

> is there a way to get to install drupalcore directly under solr and precreate that drupalcore volume so I can mount it from a host directory?

Yes, you can use `solr-create`, which starts Solr, uses Solr's standard command to create the core which puts the core directly under `solr`, then stops Solr and restarts it in the foreground:
 
```
sudo rm -fr drupalcore/
mkdir -p drupalcore
sudo chown -R 8983:8983 drupalcore
docker run  --rm --name initialsolr -v $PWD/drupalcore:/drupalcore  -v "$PWD/search_api_solr/solr-conf/6.x:/myconf/conf" -t solr:6.6  solr-create -c drupalcore -d /myconf
```
wait for that to start properly (until the logs stop printing), and leave that running.
Then copy the directory from the container into your mounted directory:
```
docker exec initialsolr bash -c "cp -r /opt/solr/server/solr/drupalcore/* /drupalcore/"
```
Now kill the initial solr container. Inspect/modify your drupalcore directory.
Then start a new one with your directory mounted in the proper location:
```
docker run --rm -v $PWD/drupalcore:/opt/solr/server/solr/drupalcore -t solr:6.6
```

**Comment by UltraBob** [comment]
Thanks, I think I has some misunderstanding about how things were actually working, and I think this clears a lot of them up.  I'll try to mess with this some more today, and comment with commands that worked for what I was trying to do.  I was testing on Mac OS X, and as you mentioned, I had problems when I actually tried to move onto the server.  One question, it appears that we are chowning the folder at the host level, docker is running as root, are the solr operations in the container running on the host as the solr user somehow?  I'm not understanding how chowning the directory at the host level beneftis the container.

**Comment by UltraBob** [comment]
That was a brilliant explanation!  Thank you!

**Comment by dsmiley** [comment]
Yeah, Martijn's answers are awesome and an education.

As an aside though... all this security stuff in Docker is depressing to me.  Perhaps I'm hopelessly naive, but as a Docker user I don't want to mess with it; I just want it to work.  I, perhaps naively, expect the very presence of containerization is usually security enough and am annoyed when I have to mess with users/groups inside the container.  Just because you can put a lock around something, doesn't mean its a good use of your time/complexity.

**Comment by makuk66** [comment]
> all this security stuff in Docker is depressing to me

I share the sentiment. Plus these ownership issues are causing the highest support load.

To be fair though, if you just do:
```
docker volume create vol3
docker run -it -v vol3:/opt/solr/server/solr/mycores solr:7.3.1 solr-precreate mycore
```
you can store your cores without having to mess with anything.
Then the main pain-points are just caused by the suboptimal layout non-empty-data-dirs, but that's not  Docker's fault.


> I just want it to work

I think we can get to a point where most scenarios are catered for without gymnastics. Keep a eye out for a PR.

**Comment by UltraBob** [comment]
My concern about using volumes was that if something somehow went wrong with docker, or I started using a native install of solr, it might be hard to retrieve the data.  Thinking about it though, from drupal I can rebuild all the data that is there by issuing a reindex order, so needing to rebuild that directory once would not be a major problem.  

Given that, maybe it does make sense to do it in docker volumes.  Now though I find that due to the requirements of the project I'm working on, I basically need to spin up three cores when building the container.  Can that also be done in a single command?  I'm thinking that I'm probably getting into the territory where a docker compose file might be a lot more sensible, though I don't see anything about multiple cores in the documentation for that either.  

I hope that when I've gotten a solid understanding of this, that I can send a pull request with a bit of expansion for the docs to cover my questions here.  I really appreciate all the help.

**Comment by UltraBob** [comment]
OK, I'd been having issues for a couple of days where my solr-precreate commands were not working as before.  I was having trouble figuring out what I was doing wrong and tracked it back to [this comment](https://github.com/docker-solr/docker-solr/issues/174#issuecomment-393399574) where you had tried to confirm what I did, and I agreed though it wasn't correct.  So I'm afraid this thread is becoming messy, but let me backtrack to clarify.  (Just for readability, first assume that I've run the following ahead of time ```docker volume create solr-data``` and ```docker volume create solr-conf``` and ```docker cp modules/contrib/search_api_solr/solr-conf/6.x/. solr-conf```, which means I have a docker volume for solr cores as solr-data and a docker volume containing the config at solr-conf.

This command does not work for me:

```
docker run \
  -v solr-data:/opt/solr/server/solr/mycores 
  -v solr-conf:/myconfig/conf 
  -d --name solr_alpine_66 -p 8984:8983 -t solr:6.6-alpine 
  solr-precreate drupalcore /myconfig
```

I get an error like:

> Cannot write to config directory /opt/solr/server/solr/mycores/drupalcore/conf; switching to use InMemory storage instead.

So solr-precreate appears to be ignoring the /myconfig/conf directive altogether and trying to write to a conf folder inside the core.  That or it is trying to copy the contents of /myconfig/conf to the core, and failing to create a conf directory to put it in.

This command does work for me, but it does seem to make the core a lot less self contained if I have to mount a volume for the core and then mount a volume for the config inside the core each time:

```
docker run \
  -v solr-data:/opt/solr/server/solr/mycores 
  -v solr-conf:/opt/solr/server/solr/mycores/drupalcore/conf
  -d --name solr_alpine_66 -p 8984:8983 -t solr:6.6-alpine 
  solr-precreate drupalcore
```

Note, that the big differences here are the mount point for the conf directory and the inclusion or exclusion of `/myconfig` at the end of the command.  In my testing I find that including or excluding /myconfig at the end of the command has no impact on its behavior.

**Comment by UltraBob** [comment]
It appears that the issue with how solr-precreate works may be a peculiarity of docker on the Mac.  I'm trying to get set up now on an ubuntu machine and it seems to not ignore the conf directory info

**Comment by UltraBob** [comment]
What I needed to do in the end was run a docker run command with solr-precreate three times, one for each core I needed.  I stopped and removed the containers in between, and the cores I created before automatically came back each time.  It may have been more sensible to create the second and third cores from within the interface, but I knew this way worked, so did it this way.  Now I don't need to mount the solr-conf volume anymore or have the solr-precreate directives, so the docker run command is a lot cleaner.  I do think either something is wrong with my environment, or solr-precreate doesn't work the same way on the mac, so that was the source of most of the confusion.  Can anyone else verify that they have the same problem with solr-precreate on the mac?

**Comment by makuk66** [comment]
> My concern about using volumes was that if something somehow went wrong with docker, or I started using a native install of solr, it might be hard to retrieve the data.

One solution for that would be to occasionally take backups: start a container that mounts both the data volume (read only) and a host directory, and just copy from one to the other.

> I basically need to spin up three cores when building the container. Can that also be done in a single command?

Sure. If you look at [solr-precreate's internals](https://github.com/docker-solr/docker-solr/blob/master/scripts/solr-precreate) you see it's designed to be easily split up to allow exactly that:

```
docker run -it -p 8080:8983 solr:7.3.1 bash -c \
  'precreate-core foo1; precreate-core foo2; precreate-core foo3; solr-foreground'
```

> which means I have a docker volume for solr cores as solr-data and a docker volume containing the config at solr-conf.

You now have 6 mounts. I'm not sure why you want those separate conf mounts. At this point it may just be simpler for you to just create the cores manually ahead of time, in a single directory, and then mount that (or copy into a volume) on mycores.

> I'm thinking that I'm probably getting into the territory where a docker compose file might be a lot more sensible, though I don't see anything about multiple cores in the documentation for that either.

You can use compose to create 3 Solr containers with a core each (each created with `solr-precreate`), exposed on different ports. If you're just using small datasets in the cores, the overhead of having 3 JVMs is a bit wasteful.

>  I do think either something is wrong with my environment, or solr-precreate doesn't work the same way on the mac

If you want people to reproduce a particular circumstances, make it as easy as possible, provide a self-contained example, and paste the full commands and output. In particular, you mention a `docker cp` but that is incomplete. From what you write it sounds like you maybe did:
```
docker rm solr_alpine_66 || true
docker volume rm solr-data solr-conf || true
test -d search_api_solr || (
  git clone git@github.com:mkalkbrenner/search_api_solr.git
  # delete the solr.install.dir line
  grep -v 'solr.install.dir' search_api_solr/solr-conf/6.x/solrcore.properties > search_api_solr/solr-conf/6.x/solrcore.properties2; mv search_api_solr/solr-conf/6.x/solrcore.properties2 search_api_solr/solr-conf/6.x/solrcore.properties )

# create the volumes
docker volume create solr-data
docker volume create solr-conf
# create a temporary container to allow copying into the volume
docker create --name copier -v solr-conf:/solr-conf bash
docker cp search_api_solr/solr-conf/6.x/. copier:/solr-conf/conf
docker rm copier
# show the 'conf' sub directory
docker run --rm -it -v solr-conf:/solr-conf bash -c "ls /solr-conf"
docker run --rm -it -v solr-conf:/solr-conf bash -c "ls /solr-conf/*"

docker run \
  -v solr-data:/opt/solr/server/solr/mycores \
  -v solr-conf:/myconfig\
  -it --name solr_alpine_66 -p 8984:8983 -t solr:6.6-alpine \
  solr-precreate drupalcore /myconfig
```

and that seems to work fine here on Mac:

```
coralw:github mak$ bash -x s.sh
+ docker rm solr_alpine_66
solr_alpine_66
+ docker volume rm solr-data solr-conf
solr-data
solr-conf
+ test -d search_api_solr
+ docker volume create solr-data
solr-data
+ docker volume create solr-conf
solr-conf
+ docker create --name copier -v solr-conf:/solr-conf bash
c086aaa9fda545964a1e4e0822821a2b7b3ad2606ca58d3b30925957575ebcfb
+ docker cp search_api_solr/solr-conf/6.x/. copier:/solr-conf/conf
+ docker rm copier
copier
+ docker run --rm -it -v solr-conf:/solr-conf bash -c 'ls /solr-conf'
conf
+ docker run --rm -it -v solr-conf:/solr-conf bash -c 'ls /solr-conf/*'
elevate.xml                  solrconfig.xml
mapping-ISOLatin1Accent.txt  solrconfig_extra.xml
protwords.txt                solrconfig_spellcheck.xml
schema.xml                   solrcore.properties
schema_extra_fields.xml      stopwords.txt
schema_extra_types.xml       synonyms.txt
+ docker run -v solr-data:/opt/solr/server/solr/mycores -v solr-conf:/myconfig -it --name solr_alpine_66 -p 8984:8983 -t solr:6.6-alpine solr-precreate drupalcore /myconfig
Executing /opt/docker-solr/scripts/solr-precreate drupalcore /myconfig
Executing /opt/docker-solr/scripts/precreate-core drupalcore /myconfig
created drupalcore
```
