### ISSUE TITLE
Mounting Volumes over Solr Owned Directories Causes Permission Errors

### ISSUE THREAD

**Issue by corbs9** [docker-solr/docker-solr#175]
If I would like to have persistence storage in an orchestrator such as DC/OS, I need to ensure that the SOLR_HOME directory can be written to by the Solr user and this is currently not possible. When mounting a volume over a Solr owned directory, the directory becomes owned by root. 

In order to resolve this, I believe that the SOLR_HOME directory should have it's ownership changed during the docker-entrypoint.db as this is the earliest point in which we can ensure that when Solr writes to this directory, it is able to. 

I believe there needs to be a few changes in the `Dockerfile` and in the `docker-entrypoint.sh` in order to allow this:
1. Ensure that the `Dockerfile` doesn't set the user to `solr`
1. Ensure that we have sudo available within the Solr image
1. Create the `$SOLR_HOME` directory and change ownership to solr:solr in the `docker-entrypoint.sh`
1. Change the exec command in `docker-entrypoint.sh` to run the command as the solr user, whilst maintaining environment variables and PATH

**Comment by makuk66** [comment]
> If I would like to have persistence storage in an orchestrator such as DC/OS 

I don't use DC/OS. If you can replicate whatever problem you're having with a set of commands that can be run with a standard docker install it's easier to experiment with and reason about.

> I need to ensure that the SOLR_HOME directory can be written to by the Solr user and this is currently not possible.

https://github.com/docker-solr/docker-solr#custom-solr_home shows how you can do that.

> I believe there needs to be a few changes in the Dockerfile and in the docker-entrypoint.sh in order to allow this:

The docker-solr image includes `gosu`, so you can do whatever you need to as root, then drop down to whatever user you want to run as. You don't need to change the docker entrypoint, you can just run whatever you like explicitly. For example:

```
docker run --user 0:0 -e VERBOSE=yes \
  -v "$PWD/mycores:/opt/solr/server/solr/mycores" "solr:7" \
  bash -c "chown -R solr:solr /opt/solr/server/solr/mycores; exec gosu solr:solr solr-precreate gettingstarted"
```

**Comment by corbs9** [comment]
@makuk66 This is similar to what is happening within DC/OS:

```
OSTML0254043:~ root# whoami
root
OSTML0254043:~ root# mkdir -p /Users/corbs/test
OSTML0254043:~ root# docker run --rm -v /Users/corbs/test:/data -e SOLR_HOME=/data -e INIT_SOLR_HOME=yes solr:7.3
copying solr home contents to /data
cp: cannot create regular file '/data/README.txt': Permission denied
cp: cannot create directory '/data/configsets': Permission denied
cp: cannot create directory '/data/lib': Permission denied
cp: cannot create directory '/data/mycores': Permission denied
cp: cannot create regular file '/data/solr.xml': Permission denied
cp: cannot create regular file '/data/zoo.cfg': Permission denied
```

I will try with the ways that you have explained above, too.

**Comment by makuk66** [comment]
Right, so chown and then run solr:
```
sudo mkdir mysolrhome
docker run --rm --user 0:0 -v "$PWD/mysolrhome:/mysolrhome" -e SOLR_HOME=/mysolrhome -e INIT_SOLR_HOME=yes solr:7.3 bash -c "chown -R solr:solr /mysolrhome; gosu solr:solr solr-foreground"
```

**Comment by corbs9** [comment]
@makuk66 I seem to be getting permission errors running those commands:

```
OSTML0254043:~ corbs$ sudo mkdir mysolrhome
OSTML0254043:~ corbs$ docker run --rm --user 0:0 -v "$PWD/mysolrhome:/mysolrhome" -e SOLR_HOME=/mysolrhome -e INIT_SOLR_HOME=yes solr:7.3 bash -c "chown -R solr:solr /mysolrhome; gosu solr:solr solr-foreground"
chown: changing ownership of '/mysolrhome': Operation not permitted
copying solr home contents to /mysolrhome
cp: cannot create regular file '/mysolrhome/README.txt': Permission denied
cp: cannot create directory '/mysolrhome/configsets': Permission denied
cp: cannot create directory '/mysolrhome/lib': Permission denied
cp: cannot create directory '/mysolrhome/mycores': Permission denied
cp: cannot create regular file '/mysolrhome/solr.xml': Permission denied
cp: cannot create regular file '/mysolrhome/zoo.cfg': Permission denied
```

**Comment by makuk66** [comment]
Strange; that works here on linux. What OS are you on?

**Comment by corbs9** [comment]
On OSX, so that could be related. 

The one thing I'm not so sure on is the use of `--user 0:0`: I'll have to find out if there is a way of doing this on an orchestrator but to me it seems a bit weird to have to run the image as a specific user in order to mount a volume. I think having this all in the image itself would be a better place to put it instead of having some of it in the image and then the rest within the run command.

**Comment by makuk66** [comment]
> On OSX

I can reproduce that. I'll look into what's going on there.

> I think having this all in the image itself would be a better place

I hear you. But I don't want to needlessly break backward compatibility, and I want to be able to support other scenarios where folks do not want to run as root when they don't have to, or where they have special requirements like OpenShift does. So making the "right" thing happen by default and other things possible is a little tricky. And I'm aware some of this may again change with future Solr changes. Exploring the various options in the various scenarios will take a little while. So if we can get you up and running in the meantime that'd be a good start.

**Comment by makuk66** [comment]
Simplifying the test-case to exclude the solr image, this fails too on OSX but works on Linux:
```
sudo mkdir mydir
docker run --user 0 -it --rm --mount "type=bind,source=$PWD/mydir,target=/mydir" bash -c "touch /mydir/myfile"
```
Reading https://docs.docker.com/docker-for-mac/osxfs/#ownership I can't really tell if behaviour this is by design. It sounds like all container volume activity ends up being mapped to the mac user on the mac fs, regardless of who you run as in the container, in which case the idea of having a root-owned directory and using it from a container running as root is probably a non-starter.

**Comment by corbs9** [comment]
Running this on mac is not really too much of a concern for me; I'd like to be able to run Solr on DC/OS and persistence storage here is currently my blocker of creating a service. I'll look into whether I can use the above command within DC/OS but I'm still not overly keen on the idea.

**Comment by ionutradu-tm** [comment]
Hey,

I have the same issue. Did you solve it @corbs9 ?

**Comment by serkandemirel0420** [comment]
> docker run --user 0:0 -e VERBOSE=yes \
>   -v "$PWD/mycores:/opt/solr/server/solr/mycores" "solr:7" \
>   bash -c "chown -R solr:solr /opt/solr/server/solr/mycores; exec gosu solr:solr solr-precreate gettingstarted"

Referance for who needs with port mapped : 

`docker run --user 0:0 -p 8983:8983 -e VERBOSE=yes \ -v "$PWD/mycores:/opt/solr/server/solr/mycores" "solr:7" \ bash -c "chown -R solr:solr /opt/solr/server/solr/mycores; exec gosu solr:solr solr-precreate test"`

**Comment by makuk66** [comment]
From `solr:8.0.0` (see [description](https://github.com/docker-solr/docker-solr/commit/6f7a6e812247d00f9f3c293993e26d6d041c119e), the only solr write permission required should be for `/var/solr`; and if you run as a non-solr user with root group it should work too.  Please try that out in DC/OS, and open a new issue if that does not succeed.
