### ISSUE TITLE
Can not access solr with host ip

### ISSUE THREAD

**Issue by smartvivien2018** [docker-solr/docker-solr#177]
I create docker image solr as below, I can access solr for http://localhost:8080/solr but can not access for host's ip address as http://xx.xx.xx.xx:8080/solr. Get error as blew, any clue to help here? Thanks!
-----------------------------------------
--2018-06-05 01:09:22--  http://XX.XX.XX.XX:8080/solr
Connecting to XX.XX.XX.XX:8080... failed: Connection refused.
-----------------------------------------
Dockfile
**_FROM centos:latest
RUN mkdir -p /opt
COPY solr-7.3.0.tgz /opt/solr-7.3.0.tgz
RUN tar -C /opt --extract --file /opt/solr-7.3.0.tgz
#RUN yum install python3-software-properties
#RUN yum install software-properties-common
#RUN echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
#RUN echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
#RUN yum install oracle-java8-installer
#RUN yum install lsof
CMD ["/bin/bash", "-c", "cd /opt/solr-7.3.0/bin; ./solr start;]_**

**Comment by makuk66** [comment]
You didn't show your actual `docker run` command, or describe what you're running this in/on, so we can't really tell. But that `solr start` you are running forks solr in the background, which is not what you want, and will cause the container to exit (check with `docker ps`). Add a `-f` to that `./solr` invocation to keep it in the foreground. If you see a Solr on `localhost:8080` without having done explicit port forwarding on your container, then perhaps you have a forgotten Solr running on port 8080 on the host itself? Solr by default listens only to localhost; that would explain why you cannot connect to the ip address.

In any case, this repository issues service is only for issues with the images produced by this repository itself, so I'll close this issue.

**Comment by smartvivien2018** [comment]
my docker run command is as below,
docker run -d -p 8080:8983  solr_730_image /bin/sh -c "tail -f /dev/null"

**Comment by smartvivien2018** [comment]
Or may I see the solr image's docker file to compare with mine?

**Comment by smartvivien2018** [comment]
I tried with solr -f as below, my OS is centos latest. But still container exited.
------------------------
./solr start -f;
------------------------
