### ISSUE TITLE
start-local-solr should check if solr is already running

### ISSUE THREAD

**Issue by socketwench** [docker-solr/docker-solr#178]
Over in ten7/flight-deck, I'm adding the ability to create cores with known schemas automatically. A problem I ran into is that the `start-local-solr` command doesn't check if Solr is already running. 

If I call start-local-solr is successive start up scripts, the command fails as the port is already allocated. Is there a way to modify the command so that it checks if solr is already running? 

Thanks!

**Comment by makuk66** [comment]
Why not just:

```
docker run -it -p 8983:8983 solr:7.3.0 bash -e -c "precreate-core core1; precreate-core core2; solr-foreground"
```

or

```
docker run -it -p 8983:8983 solr:7.3.0 bash -e -c "start-local-solr; solr create -c core1; solr create -c core2; stop-local-solr; solr-foreground"
```

?

**Comment by socketwench** [comment]
Because we're using Docker Compose, and my developers would rather just do a `docker-compose up -d` and not have to worry about any additional bespoke steps per project.

**Comment by makuk66** [comment]
> Because we're using Docker Compose, and my developers would rather just do a docker-compose up -d 

You can wrap those commands into a `docker-compose.yml` file:

```
version: "3"
services:
  solr:
    image: solr:7.3.0
    ports:
    - 8983:8983
    command: bash -e -c "precreate-core core1; precreate-core core2; solr-foreground"
```

Or if you fancy, build an image and run that:

```
mkdir dir
cat >dir/Dockerfile <<EOM
FROM solr:7.3.0
CMD bash -e -c "precreate-core core3; precreate-core core4; solr-foreground"
EOM
cat > docker-compose.yml <<EOM
version: "3"
services:
  solr:
    build: ./dir
    ports:
    - 8983:8983
EOM
docker-compose up
```

Can you be more specific about what it is you mean with "successive start up scripts" (ie provide an example I can run), and why you're trying to do doing it that specific way?

**Comment by makuk66** [comment]
Closed due to inactivity
