### ISSUE TITLE
Where is local file location for Solr in docker?

### ISSUE THREAD

**Issue by DDCR-FM** [docker-solr/docker-solr#181]
Hi,
I am new to docker-solr. I just installed docker-solr and docker-banana, how ever I cannot connect from banana to Solr. 

I can open banana's dashboard but it will show error message 
1."Collection not found at /solr/my_collection. Please check your configuration or create the collection. If you're using a proxy ensure it is configured correctly."
2."Could not retrieve collections from Solr (error status = 404)". 

Is there any link can help me with issue? Almost all link I can find about banana need to go to this adress"$SOLR_HOME/server/solr-webapp/webapp". However, since I am using docker-solr there is no such directory. 

Thanks!

**Comment by makuk66** [comment]
The instructions on https://github.com/lucidworks/banana are about running banana on the same host as your Solr instance. If you were to do that with docker, you'd have to add banana to docker-solr (so you'd create a Dockerfile that uses solr as a base, then add banana). The docker container has its webapp directory in `/opt/solr/server/solr-webapp/webapp`, so you might be able to get those instructions to work.

But the docker philosopy is to run different services in different containers, so it makes more sense to do that, and just point banana at your Solr container (using the "NOTES: If your Solr server/port is different from localhost:8983, edit banana/src/config.js and banana/src/app/dashboards/default.json to enter the hostname and port that you are using").
BTW, Google finds various other projects that have run banana under docker, eg https://github.com/mosuka/docker-banana/tree/master/1.6 and https://hub.docker.com/r/pschatzmann/banana/; they might provide some inspiration.

**Comment by DDCR-FM** [comment]
Hi, 
Mosuka's docker-banana is the exact link I followed but failed when 7th step. That;s I tried to do it in other ways. I will look into second link. I still couldn't find the webapp location. There is no such /opt/solr/server/solr-webapp/webapp.

Thanks!

**Comment by makuk66** [comment]
> There is no such /opt/solr/server/solr-webapp/webapp

There really is:

```
$ docker run -it solr bash -c "ls -l /opt/solr/server/solr-webapp/webapp"
total 44
drwxr-xr-x 3 solr solr  4096 Feb 15 20:27 WEB-INF
drwxr-xr-x 3 solr solr  4096 Jan 10  2018 css
-rw-r--r-- 1 solr solr  3262 Jan 10  2018 favicon.ico
drwxr-xr-x 4 solr solr  4096 Feb 15 20:27 img
-rw-r--r-- 1 solr solr 13253 Jan 10  2018 index.html
drwxr-xr-x 3 solr solr  4096 Jan 10  2018 js
drwxr-xr-x 2 solr solr  4096 Feb 15 20:27 libs
drwxr-xr-x 2 solr solr  4096 Feb 15 20:27 partials
```

**Comment by DDCR-FM** [comment]
So I can find it only when I do $ docker run -it solr bash -c "..."? I don't understand, is there a way I can skip this? It is because I am using docker, right?

**Comment by makuk66** [comment]
Did you figure this out?

**Comment by makuk66** [comment]
Closed due to inactivity.
