### ISSUE TITLE
Question: How can I add CORS support from docker+/-compose?

### ISSUE THREAD

**Issue by minkok3** [docker-solr/docker-solr#182]
Is there a way to add CORS support without messing around with web.xml?
All my google results points to editing the web.xml and adding new filter classes.

**Comment by makuk66** [comment]
Use a proxy. See eg:
https://github.com/shakyShane/nginx-cors-plus
https://github.com/mattbailey/docker-corsproxy

But yeah, that's a bit hand-wavy. Let's see if we can do an actual example:

```
mkdir -p nginx-content nginx-proxy/conf
cat >docker-compose.yml <<'EOM'
version: '3'
services:
  mysolr:
    image: "solr:7"
    ports:
     - "8983:8983"
    command: solr-demo
  ui:
    image: nginx
    ports:
    - "80:80"
    volumes:
      - ./nginx-content:/usr/share/nginx/html:ro
  proxy:
    image: nginx
    ports:
    - 8899:80
    volumes:
    - ./nginx-proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
EOM

cat >nginx-content/index.html <<'EOM'
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
$.get({
 url:'http://localhost:8899/solr/demo/query?debug=query&q=name:spinpoint',
 data:{},
 success:function(evt){console.log(evt);}
});
</script>
</head>
EOM

cat  >nginx-content/index-direct.html <<'EOM'
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
$.get({
 url:'http://localhost:8983/solr/demo/query?debug=query&q=name:spinpoint',
 data:{},
 success:function(evt){console.log(evt);}
});
</script>
</head>
EOM

cat >nginx-proxy/conf/nginx.conf <<'EOM'
events {
  worker_connections  4096;  ## Default: 1024
}

http {
server {
  listen 80 default_server;
  server_name localhost;

#
# Wide-open CORS config for nginx
#
  location / {
     if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        #
        # Custom headers and headers various browsers *should* be OK with but aren't
        #
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        #
        # Tell client that this pre-flight info is valid for 20 days
        #
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
     }
     if ($request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
     }
     if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
     }

    proxy_pass http://mysolr:8983;
  }

}
}
EOM

docker-compose up
```
Wait until it has started.

Now in a browser, get the JavaScript console up, and go to http://localhost/index-direct.html . You'll see "Access-Control-Allow-Origin" errors. Then go to http://localhost/index.html, and your JavaScript logs should show the solr response.

I tested this on MacOS.

Exactly how to do this configuration is a secure fashion in your scenario is left to the reader.

**Comment by minkok3** [comment]
Thank you not only pointing to the right direction but also providing a "noob-proof" example.

**Comment by ankitsinghaniyaz** [comment]
Any pointer on how to do it without proxy? To be more precise how can I modify the web.xml to configure cors?

**Comment by dsmiley** [comment]
https://opensourceconnections.com/blog/2015/03/26/going-cross-origin-with-solr/  plus googling will turn up some similar instructions.
I wish CORS was there by default, frankly.  I'm not sure if doing so would _really_ be a security problem.

**Comment by rjurney** [comment]
We can’t get CORS to work with Docker no matter what we do. We started with a JavaScript front end and moved to node.js middleware and no matter what we do we can’t get through the CORS errors. The recipe above doesn’t work. A complete solution from someone else didn’t work either. We’re on Solr 8.4.1. This is incredibly frustrating.

**Comment by AnEmortalKid** [comment]
@rjurney I had to muck with the web.xml based on [this article](https://opensourceconnections.com/blog/2015/03/26/going-cross-origin-with-solr/) but I got it work [here](https://github.com/AnEmortalKid/containment_32/blob/master/solr_system/Dockerfile#L7)

**Comment by dsmiley** [comment]
The "here" link shows a line of code preceded by a comment saying "disable cors".  Did you mean "Enable CORS"?

**Comment by AnEmortalKid** [comment]
> Did you mean "Enable CORS"?

Ah yeah sorry, I enabled CORS to allow all origins so I could get my jquery stuff hitting solr. In my head it was more 'disable this annoying thing that's making me mad right now'
