### ISSUE TITLE
Docker's Official Images Build is broken on ARMv8 (AAarch64)

### ISSUE THREAD

**Issue by lag-linaro** [docker-solr/docker-solr#190]
See [Docker's Official Images Build Server](https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/solr/) for details.

The builder receives a 404 error when attempting to fetch:

`https://github.com/tianon/gosu/releases/download/1.10/gosu-aarch64`

When the intended binary should really be:

`https://github.com/tianon/gosu/releases/download/1.10/gosu-arm64`

The issue is due to the way in which Alpine's package manager (`apk`) returns the running architecture.

Most projects expect to receive `arm64` for ARMv8 based architectures, but `apk` returns `aarch64`

**Comment by makuk66** [comment]
https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/solr/110/ shows green. Thanks Lee!
