### ISSUE TITLE
Discussion of changes for version 8

### ISSUE THREAD

**Issue by makuk66** [docker-solr/docker-solr#196]
This is an umbrella/discussion issue for a future Solr 8.

Solr 8 will most likely have some changes that will make it easier to run on Docker, which we'll want to take advantage of. For example, see the ongoing discussion on [SOLR-13035 ](https://issues.apache.org/jira/browse/SOLR-13035).

A new major version also presents an opportunity to make some non-backwards-compatible changes on the docker-solr side, which might address some long-standing pain points about ownership and permissions, and perhaps align us better with non-docker installations.

For example:
1) we can change the filesystem layout to take advantage of what SOLR-13035 will bring. Hopefully we can stop needing "mycores". 
2) we can change the filesystem layout to be more like that produced by [install_solr_service.sh](https://lucene.apache.org/solr/guide/7_6/taking-solr-to-production.html#service-installation-script) (rather than just [un-tarring](https://lucene.apache.org/solr/guide/7_6/installing-solr.html#package-installation) ). See https://github.com/docker-solr/docker-solr/issues/173. Of course, that may change in Solr 8, or not satisfy (1). And who knows how it interacts with the many other config options like `SOLR_HOME`. PR on https://github.com/docker-solr/docker-solr/pull/204
3) we can consider if we should start with `USER=root` and then use `gosu` to drop to the `solr` user, so `docker-entrypoint.sh` or `run-initdb` or a solr wrapper can `chown` the writable directories as root in orchestration platforms and environments where they can not easily be created as owned by the running user. If, after the above changes, that is indeed still needed. I don't particularly like this, but if it's the only way, now is the time.
4) we can consider always starting in single-server cloud mode (less confusing to have just one way, but I don't think I'm really in favor of that)
5) we can consider dropping the "alpine" flavour now that we have "slim", which saves 30%. Alpine has 20% further saving, but its Dockerfile is different and some of the commands are different too; removing it would simplify maintenance, speed up builds, and reduce security vulnerabilities. Basically if slim had existed when I added Alpine, I wouldn't have bothered.
6) is there a way we can retire the `start-local-solr`/`stop-local-solr` approach for `solr-create` (and `solr-demo`, though I'm less worried about that)? AFAIK the answer will be no.
7) can we switch to multi-stage builds, so that things like gpg do not end up in the image, and so we can split up the main RUN without incurring a layer (not really specific to or dependent on Solr 8). (https://github.com/docker-solr/docker-solr/pull/197 is now in master; library PR https://github.com/docker-library/official-images/pull/5256 but apparently the docker-library isn't ready for it. Reverted. May want to keep some ideas though, like having separate install scripts, and the labels and the copy-chown. Oh, but separate builder scripts are apparently a [no-no](
https://github.com/docker-solr/docker-solr/pull/130#issuecomment-459146946).
8) can we review if some of the [runtime config hacks](https://github.com/docker-solr/docker-solr/blob/master/Dockerfile.template#L69) are no longer required and can be removed. [SOLR-13087](https://issues.apache.org/jira/browse/SOLR-13087), [SOLR-13089](https://issues.apache.org/jira/browse/SOLR-13089) ... https://github.com/docker-solr/docker-solr/issues/199
9) after the above changes, can we simplify/reduce/remove the helper scripts we currently have?
10) Are there things we should be doing to make it easier to use on kubernetes, other orchestrators, app bundles etc?
11) In particular, how can we make life easier for OpenShift? See PR https://github.com/docker-solr/docker-solr/pull/203

As a side goal, it'd be good if we could do all this in a way that easily translates to a non-docker-solr Dockerfile you can easily use to create a container directly from the Solr distribution (perhaps as part of development of Solr itself). Such a Dockerfile would be simpler, as it would require less Docker Hub-specific logic (no gpg verifcation, no support for multiarch, no generate-stackbrew-library.sh etc). It's unclear if we'd want to have some/any/all scripts for such a thing. But if we could have a compatible runtime layout that would be beneficial for future maintenance.

While doing the above, we must keep backwards compatibility with current images <= 7, so they can continue to be rebuilt with newer base images and new releases. That may be somewhat challenging/messy in the docker-solr repo.

When 8 happens we may also want to retire older 6.x and 7.x versions (all but the most recent one, currently 7.6).

And there are various bits of documentation and examples that may need updating; the README and FAQ and `docs/`.

All in all there is quite a lot of possible work here, and it ties in with the Solr 8 timeline: some of the upstream work is yet to be done and may not get resolved until close to 8's release; and obviously when 8 is released, we want a docker-solr image for it as soon as possible. We'll definitely have to start working on some development branches (and discussed as separate issues) as things progress.

I wanted to write up the above thoughts to give others in the project to give an opportunity to provide feedback. Is there anything here you have strong cares about? Any insights to share? Anything I've missed?

**Comment by khushbuadav** [comment]
Getting this error for getting solr 8:

`$ docker pull solr:8
Error response from daemon: manifest for solr:8 not found`

Any idea how to resolve this? Thanks.

**Comment by makuk66** [comment]
It has not made it to the library yet. If you want to try a test version, try `dockersolr/docker-solr:8.0.0-e5b541096f5d0a93f984311a34301bc0d1acf75b`, though bear in mind that will disappear once the `solr:8.0.0` one appears.

**Comment by makuk66** [comment]
`solr:8.0.0` is in the registry now. https://github.com/docker-library/official-images/pull/5827

**Comment by sharif2008** [comment]
@makuk66  cpu usage increases to 390% for 4 core machine . is it an issue  for solr8 ?

**Comment by dsmiley** [comment]
@sharif2008 This GitHub project is only for the docker-ization of Solr.  Please look upstream and don't post here unless you've deduced the problem you report occurs only when running Solr via Docker but not without Docker.  

There is huge variability in how people use/configure Solr.  I know of this problem -- https://issues.apache.org/jira/browse/SOLR-14013  You could try and see if that bug affects you (many field values) or spend some time trying trying to use a profiler or other techniques to see what happened.  If you exhaust your investigation then post about it on the solr-user list.  Good luck.
