### ISSUE TITLE
Can I run solr image with root?

### ISSUE THREAD

**Issue by sglee18** [docker-solr/docker-solr#198]
Hello, we have a need to implement a cron job inside the container to backup Solr index. The cron service is not started by default. In order to start the cron service, the user needs to be root. Can I run Solr as root? 

Thank you.

**Comment by makuk66** [comment]
Theoretically Solr will start as root if you set the `FORCE` environment variable. But you may be causing things to become broken. I've not tested it, and I would strongly recommend against it.

How were you planning to backup from cron? If you're just copying files on disk, I would run a second container that shares the disk if your Solr one and then do your copying there. See https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes

**Comment by sglee18** [comment]
Thank you Martijn for your quick reply. Yes, we are just copying files on disk to a backup volume. We will look into the container backup strategy. It looks like instead of having cron job running inside container, we will have cron job on the host to backup the container, am I right?

**Comment by makuk66** [comment]
Right
