### ISSUE TITLE
Add help how to configure persistence (configs and index)

### ISSUE THREAD

**Issue by iBobik** [docker-solr/docker-solr#2]
There are no volumes for config files and for index, so this image as-is can not have persistence.

In README there should be example of `docker run` with `-v` parameters and explained files structure for their custom config files.

**Comment by makuk66** [comment]
There is documentation about that in https://github.com/docker-solr/docker-solr/blob/master/Docker-FAQ.md . I'll add a link to that to the README.

**Comment by iBobik** [comment]
Aha, thanks, it is helpful.

How about to also add quick summary of recommanded paths for volumes? E.g. all, only configs, only configs of one core, configs and index of one core? Many people understands how to work with Docker, but just need cheatcheet of specific paths for this image.

**Comment by makuk66** [comment]
My personal preference is to not use volumes at all; it's just simpler that way.
Yes, that means that if want to run a new version you'll have to deal with provisioning it with configuration and content, but for many use-cases that is fine. 
I certainly don't see the appeal of using different volumes for different cores and config in a typical setup.
You could put `server/logs` on a volume, but only if you want to retain those logs.
So really, if you want a recommendation for a typical setup with volumes, https://github.com/docker-solr/docker-solr/blob/master/Docker-FAQ.md#how-can-i-mount-a-host-directory-as-a-data-volume is about it.
If there are particular problems with that approach, let me know what they are.

**Comment by iBobik** [comment]
Thank you for help.
