### ISSUE TITLE
Libtensorflow does not work with alpine image

### ISSUE THREAD

**Issue by linuxswords** [docker-solr/docker-solr#201]
Using the `solr:7.6.0-alpine` image we run into following error:

```
org.apache.solr.common.SolrException: Error CREATEing XXXXX Caused by: /tmp/libtensorflow_jni4628826233287405908.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/libtensorflow_jni4628826233287405908.so)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:1087)
	at org.apache.solr.handler.admin.CoreAdminOperation.lambda$static$0(CoreAdminOperation.java:92)
	at org.apache.solr.handler.admin.CoreAdminOperation.execute(CoreAdminOperation.java:360)
	at org.apache.solr.handler.admin.CoreAdminHandler$CallInfo.call(CoreAdminHandler.java:395)
	at org.apache.solr.handler.admin.CoreAdminHandler.handleRequestBody(CoreAdminHandler.java:180)
```
going into the running container and checking the `/tmp/ directory revealed the following:

```
bash-4.4$ cd /tmp/
bash-4.4$ ls -l
total 36524
drwx------    1 root     root          4096 Jan 11 01:58 gnupg_home
drwxr-xr-x    2 solr     solr          4096 Jan 23 13:57 hsperfdata_solr
drwxr-xr-x    2 solr     solr          4096 Jan 23 13:57 jetty-0.0.0.0-8983-webapp-_solr-any-4766946392057992926.dir
-rw-r--r--    1 solr     solr      37383456 Jan 23 13:58 libtensorflow_jni4628826233287405908.so
-rw-------    1 solr     solr           298 Jan 23 13:57 start_2218284193042145008.properties
bash-4.4$ ldd libtensorflow_jni4628826233287405908.so
        ldd (0x7f95eb6e2000)
        libpthread.so.0 => ldd (0x7f95eb6e2000)
        libdl.so.2 => ldd (0x7f95eb6e2000)
        libm.so.6 => ldd (0x7f95eb6e2000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f95e8fdf000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f95e8dcd000)
        libc.so.6 => ldd (0x7f95eb6e2000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by libtensorflow_jni4628826233287405908.so)
```

The error does not exist in the `solr:7.6.0-slim` image as the alpine image uses `musl` library.

**Comment by makuk66** [comment]
How did you run the container? Something built-in, or some custom config? If the latter, just don't use the Alpine image.

**Comment by linuxswords** [comment]
I run the container in solr-cloud mode: 

```
FROM solr:7.6.0-alpine
[...]
ENTRYPOINT ["solr-foreground"]
CMD ["-cloud"]
```
We have a solr-plugin that uses  `org.tensorflow` as a dependency in a `SearchComponent`

Sure, in the meantime we switched to `solr:7.6.0-slim` but that is ~200MB bigger. It's not that big of an issue for us, but we, and maybe others would be more comfortable to use the `alpine` image

**Comment by makuk66** [comment]
> We have a solr-plugin that uses org.tensorflow as a dependency in a SearchComponent

It's obviously not possible to install every possible library that every possible solr-plugin might require; and if we did, people would complain about wasted space for stuff they didn't use.

> Sure, in the meantime we switched to solr:7.6.0-slim but that is ~200MB bigger. It's not that big of an issue for us, but we, and maybe others would be more comfortable to use the alpine image

Then the way forward is to add the required libraries in your sub image.

**Comment by linuxswords** [comment]
True - will close the issue, thx for your time!
