### ISSUE TITLE
Solr 8 docker image

### ISSUE THREAD

**Issue by alexgit2k** [docker-solr/docker-solr#208]
Solr 8 has been released 2 weeks ago on March 14th (http://lucene.apache.org/solr/news.html) and can be downloaded at: http://www.apache.org/dyn/closer.lua/lucene/solr/8.0.0/

Please offer a docker image for solr 8.

There is already a ticket for the changes for version 8 here: #196

**Comment by makuk66** [comment]
It's being actively worked on. See https://github.com/docker-solr/docker-solr/pull/207

Closing this as a duplicate
