### ISSUE TITLE
OOM Handler when solr runs in foreground

### ISSUE THREAD

**Issue by das-peter** [docker-solr/docker-solr#217]
Currently there's a potential issue when solr runs in the foreground regarding the OOM (java OutOfMemoryError) handling: https://issues.apache.org/jira/browse/SOLR-9177

The default setting of this image is to run solr in the foreground (which allows access to the console log using the `docker logs` command.). 
However, this seems to imply that java.lang.OutOfMemoryError errors won't be handled by the default `/opt/solr/bin/oom_solr.sh`, possibly leading to an unresponsive solr instance.

I've been playing around with the `-a` flag (`$SOLR_ADDL_ARGS`) when starting solr. Unfortunately I wasn't able to get it working with the default value from the [start script](https://github.com/apache/lucene-solr/blob/master/solr/bin/solr#L2123): `-XX:OnOutOfMemoryError=$SOLR_TIP/bin/oom_solr.sh $SOLR_PORT $SOLR_LOGS_DIR`
The spaces seem to cause trouble when using something like this `solr -f -a "-XX:OnOutOfMemoryError=/opt/solr/bin/oom_solr.sh 8983 /opt/solr/server/logs"`
in the default start file [`scripts/solr-foreground`](https://github.com/docker-solr/docker-solr/blob/master/scripts/solr-foreground)

So I've put the command `$SOLR_TIP/bin/oom_solr.sh $SOLR_PORT $SOLR_LOGS_DIR` into a custom script and simply used that as value for `-XX:OnOutOfMemoryError=`
That way the server seems to start just fine. However, I still have to test if the OOM handling actually kicks in and if I actually can use the env variables in the extra script or if they won't be available.

I guess for now this is just a reference to a potential problem in the hope that if someone runs into the same issue there's something to google for ;)

**Comment by das-peter** [comment]
I was able to trigger a OOM error by reducing the available memory using `SOLR_JAVA_MEM: "-Xms25m -Xmx25m"`.
1. The good news is the OOM script is properly triggered.
2. The bad news is that the ENV variables are not available. So it looks like it would be quite hard to solve this in a generic way - at least in the versions before 8. As of 8, SOLR_PORT / SOLR_HOME are defined in `/etc/default/solr` which we probably can use to solve this in a generic way.
3. The other bad news is that the default script doesn't seem to actually do anything. It creates the log file which contains `Running OOM killer script for process 1 for Solr on port 8983
Killed process 1` but the container is still running and not re-startet - as it would be expected with `restart: on-failure` set in the docker-compose file.

So as of now I figured out how to get the OOM handler activated but not yet how to make it actually generic and or do anything useful ;)

**Comment by makuk66** [comment]
> The bad news is that the ENV variables are not available. So it looks like it would be quite hard to solve this in a generic way - at least in the versions before 8. As of 8, SOLR_PORT / SOLR_HOME are defined in /etc/default/solr which we probably can use to solve this in a generic way.

In `/etc/default/solr.in.sh`. But I'd rather not set it there, as it then becomes harder to override at runtime. We could set it in the Dockerfile, but then it might be wrong in shells if it does get overridden in that file. So if we have to fix that, we may need to give it some more thought.

The `oom_solr.sh` uses SOLR_PORT / SOLR_HOME to determine the JVM's process ID. In our case there's only ever a single Solr server running, so we could write a simpler script that just does `ps auxww | grep start.jar  | grep -v grep | awk '{print $2}'`.

> The other bad news is that the default script doesn't seem to actually do anything. It creates the log file which contains Running OOM killer script for process 1 for Solr on port 8983 Killed process 1 but the container is still running

You can replicate that with a `kill -9 1` from a `docker exec`; that also does not work. Doing a `kill -HUP 1` does appear to work. The official way to address this is to run your container with `docker run --init`; Try that and report back?

Once it works, we could then look at wether to include it by default (and provide an opt-out), or just document how to opt in.

**Comment by das-peter** [comment]
@makuk66  Thank you very much for response, very much appreciated!

> we could write a simpler script that just does ps auxww | grep start.jar | grep -v grep | awk '{print $2}'.
Yeah I had the same idea just after I was testing the original oom script but hand't time to test that vector yet.  I've used your perfectly working example for my continued investigation :)

> The official way to address this is to run your container with docker run --init; 
I looked into that (aka https://github.com/krallin/tini) alongside https://github.com/Yelp/dumb-init which pretty much seem to do what's needed.
If going that way I'd say `tini` it is as it is what's behind dockers own `--init` flag,
In terms of approach I'd suggest to manually go with `tini` as relying on the `--init` flag requires knowledge. I think it's fair to assume that most of users don't have that knowledge out of the box.
And as far as I can tell `tini` is pretty much unobtrusive and unlikely to cause trouble no matter what start script is used, but this assumption definitely has to be proven.

I've created a fork #219 and adjusted the image I'm currently testing with.
So far everything looks good - the `solr-foreground` script now set's the OOM handling and the `oom_solr.sh` script successfully logs the error and kills the process.
Together with the proper docker restart policy (always, on-failure or unless-stopped) the container is restarted and solr stays responsive.

If this approach is approved I'll go ahead and change all other Dockerfiles too.

**Comment by makuk66** [comment]
> If going that way I'd say tini it is as it is what's behind dockers own --init flag

It is also documented in https://github.com/docker-library/official-images/blob/master/README.md#init

> And as far as I can tell tini is pretty much unobtrusive and unlikely to cause trouble no matter what start script is used, but this assumption definitely has to be proven.

Yeah, I'll have to look at that a bit more.

> I've created a fork #219

I've made some comments there for now.

**Comment by das-peter** [comment]
Awesome, thank you :)
