### ISSUE TITLE
Basic authentication doesn't work in solr 7.7.

### ISSUE THREAD

**Issue by tioteath** [docker-solr/docker-solr#220]
I am trying to set up [basic authentication](https://lucene.apache.org/solr/guide/7_7/basic-authentication-plugin.html#using-the-solr-control-script-with-basic-auth) using `solr:7.7`. 

I have set these variables:
```
SOLR_AUTH_TYPE="basic"
SOLR_AUTHENTICATION_OPTS="-Dbasicauth=solr:SolrRocks"
```

But after container creation solr stays unprotected.

**Comment by makuk66** [comment]
I think the section you linked to is "how to configure the Solr script to use basic authentication when it connects to a Solr server configured with basic authentication as explained above", not "just do this to make the server require basic authentication".

You'll have to do the whole `security.json` thing.
