### ISSUE TITLE
Building images of the Prometheus Exporter

### ISSUE THREAD

**Issue by HoustonPutman** [docker-solr/docker-solr#222]
Currently there is no official docker image for the [Solr Prometheus Exporter](https://lucene.apache.org/solr/guide/8_1/monitoring-solr-with-prometheus-and-grafana.html).

Prometheus is a common way of retrieving metrics from applications running in containers, so it would be nice to provide an easy way of running the prometheus exporter when running containerized Solr Cloud.

Ideally a Prometheus Exporter container would be built alongside all versions of Solr for which it exists.

**Comment by makuk66** [comment]
Per https://lucene.apache.org/solr/guide/8_1/monitoring-solr-with-prometheus-and-grafana.html:

> The Prometheus exporter is included in Solr as a contrib, and is located in contrib/prometheus-exporter in your Solr instance.

and indeed I see:

```
solr@7e10b73ad9f3:/opt/solr-8.1.1$ find . -name '*prome*'
./contrib/prometheus-exporter
./dist/solr-prometheus-exporter-8.1.1.jar
```

Looking at https://lucene.apache.org/solr/guide/8_1/monitoring-solr-with-prometheus-and-grafana.html#starting-the-exporter it looks like you just run it, with appropriate configuration, which presumably you could do in a container.

So what is it you're proposing "would be built"?

**Comment by HoustonPutman** [comment]
Oh I guess I didn't look around in the image fully enough. Thanks for the help, I'll test that out.

**Comment by dsmiley** [comment]
It would be helpful to tell users how to run the prometheus exporter from Docker; it's not obvious!
I got this to work... obviously needs adjustments based on your deployed environment.
````
docker run --rm --name solr-exporter -p 9983:9983 \
  --entrypoint=sh \
  --workdir=/opt/solr/contrib/prometheus-exporter/ \
  solr:8 \
   bin/solr-exporter -b http://host.docker.internal:8983/solr
````
The fact that bin/solr-exporter isn't executable is a small problem we should fix.  If it's executable upstream, it ought to be executable likewise in the image.
