### ISSUE TITLE
Cannot run image when authentication is on.

### ISSUE THREAD

**Issue by PradipShrestha** [docker-solr/docker-solr#225]
I am using solr 7.7.2 with authentication on. My script uses solr-create command to create core. It is creating core as intended but when checking core fails because it is trying to get status of core without credentials (line 53) and docker image terminates. If I comment those lines, image runs fine. I wonder how can I use safe checking with credentials. Is there any way I can specify credentials?

**Comment by makuk66** [comment]
`wget` supports `--user` and `--password` arguments, but they cause your credentials to show in the process list, so you don't want that. `wget` allows those options to be set in a `.wgetrc` or a `.netrc`. So if you create one of those, and use `-v` to mount it in the user home directory, it should work without any script changes. Try that. I'd link to the manual, but `gnu.org` is down at the moment.

**Comment by PradipShrestha** [comment]
@makuk66 : Thanks.
