### ISSUE TITLE
Issues connect solr container to tomcat and apache frontend

### ISSUE THREAD

**Issue by raysbudo** [docker-solr/docker-solr#228]
I've been working on connecting a solr 8 container instance to tomcat 7 container for rendering, while using an apache 2.4 container instance as the frontend static data provider.  I have solr setup with core which is created with a script at startup and is verified with the solr web UI.  I have the apache reverse proxying to both the tomcat container on 8080 and the solr container on 8983.  yet I cannot get the working solr container data to be rendered on the apache webserver after a search in done.  does anyone have a suggestion as to how to get these 3 container working together

**Comment by makuk66** [comment]
> after a search in done

Are you talking about doing a search in the admin interface? Have you seen https://support.lucidworks.com/s/question/0D58000003LRnzTCAT/how-to-configure-apache-reverse-proxy-for-solr-admin-pages?
