### ISSUE TITLE
running solr in solr user and solr group and backing up volume is creating problems.

### ISSUE THREAD

**Issue by cedric05** [docker-solr/docker-solr#232]
https://github.com/docker-solr/docker-solr/blob/master/6.6/Dockerfile#L16-L18

in be above code lines, its specified that solr container should be running in solr 8983 and solr userid 8983.
in our scenario, we separate out config and storage in core.properties.
`docker volume create solr-volume` is creating volume with default user.
solr is failing with permission issue.

**Comment by cedric05** [comment]
workaround would be

`docker exec  -it $SOLR_CONTAINER_ID --user root bash`
```
chown -R solr:solr /opt/solr_volume
```
then use /opt/solr_volume

**Comment by makuk66** [comment]
Right, that's just the way Docker works.

Any particular reason you're using the old 6.6?

You can do that without the `docker exec` too, by running the solr container as root, then switching to the solr user using `gosu`:

```
docker run --user 0:0 -v "solr-volume:/opt/solr_volume" solr:6.6 bash -c "chown -R solr:solr /opt/solr_volume; exec gosu solr:solr solr-precreate gettingstarted"
```

With the latest version 8.1 it's even easier:

```
docker run -it -v solr-volume2:/var/solr solr:8.1 solr-precreate getting-started
```

**Comment by cedric05** [comment]
thanks @makuk66 .
our application tied with solr 6.6. we will  have to migrate to latest version. 
this really solved my problem.
