### ISSUE TITLE
JCMD chances

### ISSUE THREAD

**Issue by yael-lorenzo** [docker-solr/docker-solr#235]
I would like to know if you are considering installing jcmd.

If not, what is the best option to go in your opinion?

Thanks in advanced.

**Comment by makuk66** [comment]
> I would like to know if you are considering installing jcmd.

In general I'm disinclined to add extra tooling beyond what we inherit from the base image.

But it appears we already have `jcmd`:
```
mak» docker run -it solr:8.1 bash -c "jcmd --help"   

Usage: jcmd <pid | main class> <command ...|PerfCounter.print|-f file>
```


> what is the best option to go in your opinion?

Use the above from the latest images. Other options typically are: make a custom Dockerfile to add what you want, or mount a volume with tools, or connect over the network from the tool in a different container, either over the network through exposed ports or by using the `reuse another container's network stack` using localhost.

**Comment by yael-lorenzo** [comment]
Thanks for the quick reply, I am using Solr 7.7 but I will take a look. =)

**Comment by makuk66** [comment]
It's there for 7.7 too:
```
docker-solr» docker run -it dockersolr/docker-solr:7.7 bash -c "jcmd --help"  
Usage: jcmd <pid | main class> <command ...|PerfCounter.print|-f file>
```
