### ISSUE TITLE
Push test builds to docker hub

### ISSUE THREAD

**Issue by makuk66** [docker-solr/docker-solr#24]
The automated builds should publish test builds to docker hub, so team members can easily test without having to build locally.

**Comment by makuk66** [comment]
I've created an organisation on hub.docker.com https://hub.docker.com/u/dockersolr/.
I would have liked it to be "docker-solr" for consistency with this github organisation, but dashes are currently not allowed: https://github.com/docker/hub-feedback/issues/373
This organisation hosts a https://hub.docker.com/r/dockersolr/docker-solr/ repository.
I've created a hub user https://hub.docker.com/u/dockersolrbuilder/, with an associated github user https://github.com/docker-solr-builder.
I've added a "push_all" to the https://github.com/docker-solr/docker-solr/blob/master/build-all.sh script, and added required environment variables to the Travis web UI, so that it can use the "dockersolrbuilder" user to publish to the https://hub.docker.com/r/dockersolr/docker-solr/ repository on every build.

So you can now run the `dockersolr/docker-solr:6.0` image, and get the latest testing build.
To set expectations: these may be broken in any number of ways during development.
If you want stability, use the official builds from https://hub.docker.com/_/solr/

**Comment by sylus** [comment]
Thanks so much for this!
