### ISSUE TITLE
Solr-HdfsDirectoryFactory

### ISSUE THREAD

**Issue by DwaneHall** [docker-solr/docker-solr#243]
Hey Martijn,
Thanks for all of your work on this project it's an extremely useful project particularly for teams managing large Solr cloud deployments like us.  I have more general inquiry rather than issue regarding Solr on Docker.  Have you ever seen or attempted a deployment of Solr-Docker with indexes stored on Hdfs (HdfsDirectoryFactory) rather than local disk? I've been playing around with the image for a few days and always hit issues communicating from within Docker to Hdfs particularly with Kerberos authentication.  It seems possible to accomplish as the directory factory options can be passed across to Solr easily as environment variables.  
```
SOLR_OPTS: "-Dsolr.directoryFactory=HdfsDirectoryFactory -Dsolr.lock.type=hdfs -Dsolr.hdfs.home=hdfs://MYHADOOPLOC/data/TEST_HDFS/solr -Dsolr.hdfs.confdir=/usr/hdp/current/hadoop-client/conf -Dsolr.hdfs.security.kerberos.keytabfile=/dev/dockerFiles/solr.service.keytab -Dsolr.hdfs.security.kerberos.principal=solr@MYDOMAIN -Dsun.security.spnego.debug=true -Dsun.security.krb5.debug=true -Djava.security.krb5.conf=/hostroot/etc/krb5.conf"
```
I guess I'm just trying to determine if this type of configuration is even possible to accomplish, some of the possible gotcha's to watch out for, and if there was some sample configurations available as they'd be a really useful addition to the documentation for sites running Solr on Hdfs.  

Thanks again for all your work on this.

**Comment by makuk66** [comment]
Hi Dwane,

Thanks for your kind words.

I imagine this is possible, but I don't have personal experience of that configuration, so don't have any gotchas or examples. I'm not aware of any elsewhere either; perhaps someone else will jump in with some pointers.

For the specific errors you're seeing I would suggest you have a look at `xxd /proc/1/cmdline` (or `ps`) in the container to double-check that the command line options in your setup got passed to the JVM correctly. It would also be helpful to see the exact error messages from the logs. If you do end up producing a configuration+instructions for a demo I'll be happy to add that to https://github.com/docker-solr/docker-solr-examples.

**Comment by DwaneHall** [comment]
Thanks for getting back to me so quickly Martijn. I'll be sure to document my findings and I'd be happy to contribute them to the examples section if I get everything up and running.  I think I'm pretty close to cracking it but our Hdfs/Solr setup is a little unusual so it may not satisfy all use cases for the community (we're unable to run swarm and have to use the host network for our containers).  Hopefully there's still enough useful information to help others running Solr on Hdfs. 

(Thanks for the edits to my original post and label addition I'm just getting familiar with all of the GitHub features).

**Comment by DwaneHall** [comment]
Hey Martijn,
Just closing out this thread regarding use of the HdfsDirectoryFactory with the Solr Docker image for others in a similar position.    As you mentioned it is possible to run Solr (Docker) on Hdfs but a few configuration changes will need to be made before it is possible.   The primary issue is Java compatibility with Hadoop which currently only supports [Java 8](https://cwiki.apache.org/confluence/display/HADOOP/Hadoop+Java+Versions).  With the Solr Docker versions 7/8 using Java 11 this will cause incompatibility errors with the Java security classes.  This leaves a few options for people wanting to take this route. 

Use the Solr 6x image which uses Java 8 as the default JVM
Create a custom Docker File to use Java 8 for the Docker 7x or 8x branch

Version Tested
Hadoop/YARN 2.7.3

Kevin Risden has done some great work with updating the Hadoop libraries in the 8x Solr branch so it is compatible with the 3x version of Hadoop but I have not tested the configuration in this environment. I suspect the Java comparability issues will remain until [Hadoop-15338](https://issues.apache.org/jira/browse/HADOOP-15338) is complete.

Thanks,

Dwane

**Comment by makuk66** [comment]
Thanks for the information. All these different Java version compatibly issues are unfortunate; and yes I think we'll have to wait until this gets resolved upstream.
