### ISSUE TITLE
Using Solr Basic Authentication Plugin with Docker-Compose

### ISSUE THREAD

**Issue by jasi110** [docker-solr/docker-solr#246]
I'm trying to use the basic authentication plugin in a docker-compose.yaml file. I have the SOLR_AUTH_TYPE and SOLR_AUTHENTICATION_OPTS in the environment section, I have the security.json volume mounted and I can see it in the container. It has owner and group of 8983, and I need to use the bin/solr script to put security.json into zookeeper. I'm trying to do this with:
command:
- bin/solr zk cp file:/opt/solr/server/solr/security.json zk:/security.json
But this fails with a file or directory not found. From some research, it seems the entrypoint.sh may not be finding this, but I'm unsure.
Any assistance is greatly appreciated.
Thanks.

**Comment by makuk66** [comment]
Can you copy-paste the exact and complete docker-compose.yaml and output? I'm not clear what file or directory  is not found. It could be you're providing the command badly, or the security.json is not where you think it is.

**Comment by jasi110** [comment]
I looked more closely at the command and I did not quote it properly.  I've fixed that and there is no problem remaining.  Thanks for your insight.

**Comment by amandalmia14** [comment]
@jasi110  It will be great if you can share the docker-compose file and the security json file.

**Comment by weiklr** [comment]
got it working by doing this in docker-compose: 
really think that this should be documented somewhere, especially if we wanna programatically create configsets via the rest api, which requires basic auth to be setup.

```yaml
command: bash -c "bin/solr zk cp file:/var/solr/data/security.json zk:/security.json && solr-foreground"
```

**Comment by makuk66** [comment]
Add `exec` in front of that `solr-foreground`.

**Comment by fakabbir** [comment]
Is there any place to get security.json file ?

**Comment by weiklr** [comment]
You can easily get a sample by looking up security.json from the solr docs

**Comment by weiklr** [comment]
> Add `exec` in front of that `solr-foreground`.

Done! If this is useful, I dun mind submitting a pr to document this down
