### ISSUE TITLE
Documentation on docs.docker.com/dockerhub outdated

### ISSUE THREAD

**Issue by aguilarm** [docker-solr/docker-solr#249]
The documentation on both https://docs.docker.com/samples/library/solr/ and https://hub.docker.com/_/solr seems to be a bit stale. It does not mention the version 8 adjustments but does have the v8 tags.

Just making sure ya'll were aware of it, spent a bit debugging mycores until I decided to go to github.

**Comment by makuk66** [comment]
Thanks for letting me know. Yeah it's annoying the way that is not done automatically. Let's see if we can fix that once and for all.
