### ISSUE TITLE
Dockerfile error

### ISSUE THREAD

**Issue by biggosh** [docker-solr/docker-solr#253]
I'm tring to use the following Dockerfile to create a cutom image for my project

```
FROM solr:8.2
SHELL ["/bin/bash", "-c"]

RUN /opt/docker-solr/scripts/solr-create -c test
ADD solrconfig.xml /var/solr/data/test/conf
ADD managed-schema /var/solr/data/test/conf

EXPOSE 8983
```

When I run docker build the process hangs with 

> OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory.

error.

May someone help me?

thanks

**Comment by makuk66** [comment]
The solr-create script is intended to run at "docker run" time. It starts Solr in the background on localhost, creates a core with "solr create", stops Solr, and then starts Solr in the foreground to serve requests. If this happens during your "docker build", it will make your build hang.

There are various ways of creating a collection. The preferred way is to just mount your config using a volume, then run solr-precreate when you run the container. See https://github.com/docker-solr/docker-solr/blob/master/README.md#creating-cores and https://github.com/docker-solr/docker-solr-examples/tree/master/custom-configset. This does not require a custom docker image, is quick, and works when you mount an empty /var/solr/data to hold your data in a volume.

**Comment by biggosh** [comment]
Thank for the suggestions,
