### ISSUE TITLE
Publish 8.3 docker image

### ISSUE THREAD

**Issue by mballoni** [docker-solr/docker-solr#259]
Do we have a date for publishing the 8.3 to docker registry?
 I'm not able to download it:

Error response from daemon: manifest for solr:8.3.0 not found: manifest unknown: manifest unknown

Error response from daemon: manifest for solr:8.3 not found: manifest unknown: manifest unknown

Docker registry is also not listing it there:

https://hub.docker.com/_/solr/

Thank you,

**Comment by makuk66** [comment]
It's coming. Might be tomorrow, or next week. Some JVM changes and testing delayed it a bit, see discussion on https://github.com/docker-solr/docker-solr/issues/231

**Comment by makuk66** [comment]
https://github.com/docker-library/official-images/pull/6938

**Comment by mballoni** [comment]
Thank you @makuk66 , I apologize for the inconvenience.

**Comment by makuk66** [comment]
8.3.0 is now on the hub:

```
mak» docker pull solr:8.3.0  
8.3.0: Pulling from library/solr
Digest: sha256:42f738039261305903a48afefd811a41579bae036a1bd56a3b47a5d546b2baca
Status: Image is up to date for solr:8.3.0
docker.io/library/solr:8.3.0
```
