### ISSUE TITLE
Update Solr 8.3 to 8.3.1

### ISSUE THREAD

**Issue by jaceq** [docker-solr/docker-solr#265]
Hello,

I see solr 8.3.1 is out: https://lucene.apache.org/solr/8_3_1/changes/Changes.html
Could you, please update 8.3 tag to 8.3.1 ?

(If this helps I can make a PR - please let me know).

Thanks

**Comment by makuk66** [comment]
We're working on iy

**Comment by makuk66** [comment]
See https://github.com/docker-library/official-images/pull/7082

**Comment by jaceq** [comment]
@makuk66 Cool, thank you for info!

**Comment by makuk66** [comment]
Now available from [Docker hub](https://hub.docker.com/layers/solr/library/solr/8.3.1/images/sha256-3c32c6268a422d4fa0add3d974d108fb547d099018ea18b8ddd66ee3a8d7937c)
