### ISSUE TITLE
container solr 

### ISSUE THREAD

**Issue by issahamieh** [docker-solr/docker-solr#269]
hello, how can create index in this container ?

**Comment by makuk66** [comment]
https://github.com/docker-solr/docker-solr#creating-cores

**Comment by issahamieh** [comment]
@makuk66 am copy my data into container solr now how can show my data?

**Comment by makuk66** [comment]
https://github.com/docker-solr/docker-solr#running-solr-with-host-mounted-directories

> with a web browser go to http://localhost:8983/ to see the Admin Console (adjust the hostname for your docker host). In the web UI if you click on "Core Admin" you should now see the "gettingstarted" core.

> In the UI, find the "Core selector" popup menu and select the "gettingstarted" core, then select the "Query" menu item. This gives you a default search for *:* which returns all docs. Hit the "Execute Query" button, and you should see a few docs with data. Congratulations!

**Comment by issahamieh** [comment]
@makuk66 sorry my friend, my problem here is about the container let me explain to you 
am building a container solr:latest and solr 8.
i have a data in my desktop am copy in the container solr with command (docker cp /home/issa/Desktop/TRIALOG_configs 257e91aa0d55:/TRIALOG_configs
)
the index was creating is TRIALOG_configs with the command (docker exec -it --user=solr 257e91aa0d55 bin/solr create_core -c TRIALOG_configs -d TRIALOG_configs

)

now i want to put the data was copying in container solr in the idex was creating (TRIALOG_configs) 
how can do it??

**Comment by makuk66** [comment]
What is in TRIALOG_configs -- solr core config, or log data data files you want load, or both? Either way you probably don't want to use `docker cp`.

If it's config, then [here is an example](https://github.com/docker-solr/docker-solr-examples/tree/master/custom-configset#using-a-custom-configset) of how to do that -- once you have the config you want, you can use it [like this](https://github.com/docker-solr/docker-solr-examples/tree/master/custom-configset#using-the-configset).

If it's data, then see [these instructions](https://github.com/docker-solr/docker-solr#loading-your-own-data) on how to do that from a separate container invocation with `docker run`. Alternatively you can mount the data into your server container, and use your `docker exec` into that.

**Comment by issahamieh** [comment]
@makuk66 TRIALOG_configs is a folder of the configuration , and i have a folder of data .
firstly i want to put the configuration (fields of schema) 
secondly i want to put the data 
i copies the 2 folder the configuration and data inside container but to now i don't know how i can put the data in the index and the field to schema plz help me for this 
thank you

**Comment by issahamieh** [comment]
@makuk66 hello, how can put the schema in solr version 5 or any version ?

**Comment by dsmiley** [comment]
The questions here are a bit rudimentary; you will have to become more familiar with Solr and docker.

BTW, if putting your configuration into the image is awkward (and I sympathize; it is), a very different way of configuring Solr is entirely by it's web API _instead of_ editing/providing config files directly.  See the "Schema API" https://lucene.apache.org/solr/guide/6_6/schema-api.html    In this approach you start with Solr's default and then you run a script to manipulate it to have the schema you want.  This is fundamentally different than _giving_ the schema to Solr.  You could do this by basically posting a large JSON file of schema manipulation commands.

**Comment by epugh** [comment]
This issue looks closable ;-)
