### ISSUE TITLE
Get rid of "shared memory" warnings

### ISSUE THREAD

**Issue by janhoy** [docker-solr/docker-solr#273]
When starting the docker image you typically see these log lines:

    Starting Solr 8.4.0
    OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
    OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
    OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
    ...

What is the cause of these and how can we get rid of them?

**Comment by janhoy** [comment]
https://support.pingidentity.com/s/article/Addressing-Failed-to-reserve-shared-memory-errors

**Comment by makuk66** [comment]
I can confirm that, per [Java Support for Large Memory Pages](https://www.oracle.com/technetwork/java/javase/tech/largememory-jsp-137182.html):

```
root@vm101:~# echo 4294967295 > /proc/sys/kernel/shmmax
root@vm101:~# echo 1536 > /proc/sys/vm/nr_hugepages
```

in the host, makes the errors go away.

I'm not sure that there's anything we can do about this, other than removing `XX:+UseLargePages`, but that's an upstream default.

**Comment by janhoy** [comment]
Ok, I don't know the origin of those settings, but it should probably result in some documentation change.

Now that the image is official, we should add a new page to the Reference Guide about running Solr under Docker and that page should mention such host settings.

**Comment by ctargett** [comment]
Not sure if it helps, and you might already know, but it is possible to have a page in the Ref Guide where the content is pulled from another source at build-time. If the Ref Guide page would be some kind of near-copy of the README, you could just `include` the README (or sections of it) so maintenance is in a single source of truth only packaged in different ways.

**Comment by bradjones1** [comment]
For what it's worth, if your installation can run without huge pages or you do not require it, seems the least-friction way to implement this is to include an option in your `GC_TUNE` env var so disable this in the JVM:

`GC_TUNE="-XX:-UseLargePages"`

**Comment by dsmiley** [comment]
This is an issue for the Solr project, not specific to the Docker aspect.  I'm closing.

**Comment by epugh** [comment]
https://github.com/apache/lucene-solr/pull/2304
