### ISSUE TITLE
Add some bash aliases

### ISSUE THREAD

**Issue by janhoy** [docker-solr/docker-solr#290]
When exec-ing into the image, I´d like aliases such as

    alias ll="ls -l"

Any other wishes?

**Comment by dsmiley** [comment]
I'd rather we not mess with such things, and thus keep things vanilla & simple..

**Comment by janhoy** [comment]
It´d be fairly standard like e.g:

    cat <<EOF >>/etc/profile
    export LS_OPTIONS='--color=auto'
    alias ls='ls $LS_OPTIONS'
    alias ll='ls $LS_OPTIONS -l'
    EOF

Not a big deal though, just miss it every time I exec into Solr containers :)

**Comment by dsmiley** [comment]
But it has nothing to do with Solr.  Arguably, you should take up this cause at various layers upstream.  At least it would have a greater impact that just this container.  I do appreciate that it's annoying when SSH'ing to some place and the configuration isn't my preference but such is life.

**Comment by makuk66** [comment]
Yeah let's just not. These are personal preferences. Redefining `ls` in particular does not seem wise. You could of course always mount a `.profile` into your container :-)
