### ISSUE TITLE
why solr installed folder ownship change to root

### ISSUE THREAD

**Issue by realcaiying** [docker-solr/docker-solr#292]
i found this changes in Dockerfile between 7.7 and 8.0+

```shell
# solr 7.7 Dockerfile
...
110  chmod -R 0755 /opt/solr/server/scripts/cloud-scripts; \
111  chown -R "$SOLR_USER:$SOLR_GROUP" /opt/solr /docker-entrypoint-initdb.d /opt/docker-solr; \
112  chown -R "$SOLR_USER:$SOLR_GROUP" /opt/mysolrhome; \
...
```

```shell
# solr 8.0 Dockerfile
...
127  chown -R "0:0" /opt/solr-$SOLR_VERSION /docker-entrypoint-initdb.d /opt/docker-solr; \
128  chown -R "$SOLR_USER:0" /var/solr; \
...
```

now i use the helm chart in kubernetes, i want add ikanalyzer support and DIH feature to solrcloud, 

as in my opinion, 

i need copy some jars and config file to `/opt/solr/server/solr-webapp/webapp/WEB-INF/classes` and `/opt/solr/server/solr-webapp/webapp/WEB-INF/lib`

use command like 

`kubectl cp classes solr-test-0:/opt/solr/server/solr-webapp/webapp/WEB-INF/classes`

etc.

i just own the solr user privilege cannot do this, so how should i do is your recommend way.

and i want to know the reason why change the folder ownship plz.

**Comment by makuk66** [comment]
> i want to know the reason why change the folder ownship plz.

See https://github.com/docker-solr/docker-solr/issues/196 for a discussion of ownership changes. The main idea was to have `/opt/solr` read-only and have all writable things in `/var/solr`

> i just own the solr user privilege cannot do this, so how should i do is your recommend way.

Mount a volume containing the desired files?

**Comment by realcaiying** [comment]
thanks for your response.
