### ISSUE TITLE
Is it possible to access the solr-exporter in Docker?

### ISSUE THREAD

**Issue by mutanthumb** [docker-solr/docker-solr#300]
Hi, I'm somewhat new to Docker and was hoping to explore the "solr-exporter" feature for Prometheus (https://lucene.apache.org/solr/guide/7_3/monitoring-solr-with-prometheus-and-grafana.html). I can't locate "contrib/prometheus-exporter" within the container. I'm running this on MacOSX. The solr Docker instance is running fine and I can use the Admin Console run a query but I'm not sure how I would navigate to this "./bin/solr-exporter".  Any advice would be great, thank you! -susan

**Comment by makuk66** [comment]
solr-exporter is in the image:

```
solr@d9cbc40481f6:/opt/solr-8.5.0$ find . -name '*exporter*'
./contrib/prometheus-exporter
./contrib/prometheus-exporter/bin/solr-exporter
./contrib/prometheus-exporter/bin/solr-exporter.cmd
./contrib/prometheus-exporter/conf/solr-exporter-config.xml
```

so you could run it with something like:

```
docker network create mysolr
# start solr
docker run -it --name mysolr --network mysolr solr
# run a separate container for prometheus-exporter and point it to solr
docker run -it --network mysolr solr:8 bash -c "set -x; cd contrib/prometheus-exporter; ./bin/solr-exporter -p 9854 -b http://mysolr:8983/solr -f ./conf/solr-exporter-config.xml -n 8"                                 
```

It depends a bit on where/how you want to deploy it. If you don't want to use networks, and you're on a Mac you could do:

```
docker run -it -p 8877:8983 --name mysolr2 solr 
docker run -it solr:8 bash -c "set -x; cd contrib/prometheus-exporter; ./bin/solr-exporter -p 9854 -b http://host.docker.internal:8877/solr -f ./conf/solr-exporter-config.xml -n 8"                                    
```

**Comment by mutanthumb** [comment]
Great thank you, I'll give that a go!

**Comment by mutanthumb** [comment]
Found it, I wasn't in the right CLI. Thanks!
