### ISSUE TITLE
When I Build docker 6 I get a no such file error on osx

### ISSUE THREAD

**Issue by turbopape** [docker-solr/docker-solr#31]
I downloaded the Dockerfile for the 6.0.0 version,

I am on osx.

When I try to build the image, I get:
Removing intermediate container 6af39af5996d
Step 14 : COPY scripts /opt/docker-solr/scripts
lstat scripts: no such file or directory
And the image is not built.
Thanks for your assistance

**Comment by makuk66** [comment]
You can't just download a Dockerfile; you need the complete repo, and then you can do:

```
cd 6.0
docker build -t mysolr6 .
```

The maintenance scripts for the whole repo (the ones that create the files in the subdirectories) run on linux only.
