### ISSUE TITLE
Script wait-for-solr.sh is not working

### ISSUE THREAD

**Issue by jeetchris** [docker-solr/docker-solr#310]
Hi,

I have been trying to use the wait-for-solr.sh script to initialize a solr instance in local (Mac, docker-machine).
But the script is simply replying that solr is not running yet.
I guess the issue is related to bash options used at the top of the script, because if I run the wget command directly inside the container, it works correctly.
Solr Admin UI is also accessible from Mac.

I can reproduce the issue on both solr:7.1.0 and solr:8.5.1 images.

Also, if I use the script directly within solr machine (so using localhost by default), it just hangs. I suppose until timeout, but did not wait a long time.

docker-compose.yml
```yaml
version: '3'
services:
  solr:
    image: solr:8.5.1
    ports:
      - 8983:8983
  solr-init:
    image: solr:8.5.1
    command: bash -c "wait-for-solr.sh --solr-url http://solr:8983"
```
```bash
$ docker-compose up
Creating network "solr_default" with the default driver
Creating solr_solr_1      ... done
Creating solr_solr-init_1 ... done
Attaching to solr_solr-init_1, solr_solr_1
solr_1       | Starting Solr
solr_1       | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
solr_1       | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
solr_1       | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
solr_1       | 2020-05-07 04:18:15.152 INFO  (main) [   ] o.e.j.u.log Logging initialized @1696ms to org.eclipse.jetty.util.log.Slf4jLog
solr_1       | 2020-05-07 04:18:15.506 INFO  (main) [   ] o.e.j.s.Server jetty-9.4.24.v20191120; built: 2019-11-20T21:37:49.771Z; git: 363d5f2df3a8a28de40604320230664b9c793c16; jvm 11.0.7+10
solr_1       | 2020-05-07 04:18:15.577 INFO  (main) [   ] o.e.j.d.p.ScanningAppProvider Deployment monitor [file:///opt/solr-8.5.1/server/contexts/] at interval 0
solr_1       | 2020-05-07 04:18:16.052 INFO  (main) [   ] o.e.j.w.StandardDescriptorProcessor NO JSP Support for /solr, did not find org.apache.jasper.servlet.JspServlet
solr_1       | 2020-05-07 04:18:16.070 INFO  (main) [   ] o.e.j.s.session DefaultSessionIdManager workerName=node0
solr_1       | 2020-05-07 04:18:16.074 INFO  (main) [   ] o.e.j.s.session No SessionScavenger set, using defaults
solr_1       | 2020-05-07 04:18:16.081 INFO  (main) [   ] o.e.j.s.session node0 Scavenging every 660000ms
solr_1       | 2020-05-07 04:18:16.227 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter Using logger factory org.apache.logging.slf4j.Log4jLoggerFactory
solr_1       | 2020-05-07 04:18:16.238 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter  ___      _       Welcome to Apache Solr™ version 8.5.1
solr_1       | 2020-05-07 04:18:16.239 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter / __| ___| |_ _   Starting in standalone mode on port 8983
solr_1       | 2020-05-07 04:18:16.239 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter \__ \/ _ \ | '_|  Install dir: /opt/solr
solr_1       | 2020-05-07 04:18:16.244 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter |___/\___/_|_|    Start time: 2020-05-07T04:18:16.244189Z
solr_1       | 2020-05-07 04:18:16.323 INFO  (main) [   ] o.a.s.c.SolrResourceLoader Using system property solr.solr.home: /var/solr/data
solr_1       | 2020-05-07 04:18:16.331 INFO  (main) [   ] o.a.s.c.SolrXmlConfig Loading container configuration from /var/solr/data/solr.xml
solr_1       | 2020-05-07 04:18:16.467 INFO  (main) [   ] o.a.s.c.SolrXmlConfig MBean server found: com.sun.jmx.mbeanserver.JmxMBeanServer@b978d10, but no JMX reporters were configured - adding default JMX reporter.
solr_1       | 2020-05-07 04:18:17.428 INFO  (main) [   ] o.a.s.h.c.HttpShardHandlerFactory Host whitelist initialized: WhitelistHostChecker [whitelistHosts=null, whitelistHostCheckingEnabled=true]
solr_1       | 2020-05-07 04:18:17.705 WARN  (main) [   ] o.e.j.u.s.S.config Trusting all certificates configured for Client@7487b142[provider=null,keyStore=null,trustStore=null]
solr_1       | 2020-05-07 04:18:17.706 WARN  (main) [   ] o.e.j.u.s.S.config No Client EndPointIdentificationAlgorithm configured for Client@7487b142[provider=null,keyStore=null,trustStore=null]
solr_1       | 2020-05-07 04:18:17.998 WARN  (main) [   ] o.e.j.u.s.S.config Trusting all certificates configured for Client@476fe690[provider=null,keyStore=null,trustStore=null]
solr_1       | 2020-05-07 04:18:17.998 WARN  (main) [   ] o.e.j.u.s.S.config No Client EndPointIdentificationAlgorithm configured for Client@476fe690[provider=null,keyStore=null,trustStore=null]
solr-init_1  | Solr is not running yet on http://solr:8983. 11 attempts left
solr_1       | 2020-05-07 04:18:18.033 WARN  (main) [   ] o.a.s.c.CoreContainer Not all security plugins configured!  authentication=disabled authorization=disabled.  Solr is only as secure as you make it. Consider configuring authentication/authorization before exposing Solr to users internal or external.  See https://s.apache.org/solrsecurity for more info
solr_1       | 2020-05-07 04:18:18.393 INFO  (main) [   ] o.a.s.c.TransientSolrCoreCacheDefault Allocating transient cache for 2147483647 transient cores
solr_1       | 2020-05-07 04:18:18.397 INFO  (main) [   ] o.a.s.h.a.MetricsHistoryHandler No .system collection, keeping metrics history in memory.
solr_1       | 2020-05-07 04:18:18.544 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.node' (registry 'solr.node') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@b978d10
solr_1       | 2020-05-07 04:18:18.547 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jvm' (registry 'solr.jvm') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@b978d10
solr_1       | 2020-05-07 04:18:18.560 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jetty' (registry 'solr.jetty') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@b978d10
solr_1       | 2020-05-07 04:18:18.620 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Found 0 core definitions underneath /var/solr/data
solr_1       | 2020-05-07 04:18:18.735 INFO  (main) [   ] o.e.j.s.h.ContextHandler Started o.e.j.w.WebAppContext@51f49060{/solr,file:///opt/solr-8.5.1/server/solr-webapp/webapp/,AVAILABLE}{/opt/solr-8.5.1/server/solr-webapp/webapp}
solr_1       | 2020-05-07 04:18:18.763 INFO  (main) [   ] o.e.j.s.AbstractConnector Started ServerConnector@4de41af9{HTTP/1.1,[http/1.1, h2c]}{0.0.0.0:8983}
solr-init_1  | Solr is not running yet on http://solr:8983. 10 attempts left
solr-init_1  | Solr is not running yet on http://solr:8983. 9 attempts left
solr-init_1  | Solr is not running yet on http://solr:8983. 8 attempts left
[...]
```
```bash
$ docker-compose run --rm solr-init bash
solr@fe71326e46c0:/opt/solr$ solr_url=http://solr:8983
solr@fe71326e46c0:/opt/solr$ if wget -q -O - "$solr_url" | grep -q -i solr; then echo "OK"; else echo "NOK"; fi
OK
solr@fe71326e46c0:/opt/solr$ solr_url=http://solr:8080
solr@fe71326e46c0:/opt/solr$ if wget -q -O - "$solr_url" | grep -q -i solr; then echo "OK"; else echo "NOK"; fi
NOK
solr@fe71326e46c0:/opt/solr$ wait-for-solr.sh --solr-url http://solr:8983
solr is not running yet on http://solr:8983. 11 attempts left
solr is not running yet on http://solr:8983. 10 attempts left
[...]
```

I am wondering if I am the only one with this issue, and if it is the case, what am I doing wrong? because I noticed several people saying that the script works for them in the other issues.

**Comment by makuk66** [comment]
Your `docker-compose.yml` works for me on Docker Desktop on the Mac, and on Linux; the `solr-init` containers correctly exits 0.
Your manual commands do what the script does, so I cannot see why that would not work. 

You can try setting VERBOSE=true in you init container, and make sure that it executes what we think. Next for debugging you could copy the script to local (and mount it back to your container), and try immediately after the `while` to just run `wget -v -q -O - "$solr_url"` and see what that does compared to manual tests.

**Comment by jeetchris** [comment]
Thank you for your fast answer.

First thing to consider: as I wrote, I run this under `docker-machine`, not localhost docker (reasons are various: tests using docker swarm, no port conflicts, easy cleaning of the memory, no difference with Windows, etc. during my work).

- Yes, I had tried `VERBOSE=yes` and editing the script myself directly. It never reaches the break.

- If I remove the `-q` option to the grep, the script works fine (successes when it needs, and fails if I change the tested port for instance), but we get the output of the grep too in the logs.

- If I remove the `pipefail` option to the bash script at the top, it works perfectly. Which is why I suggested it may be related to bash options. But we get the output of `bash -o` command.

- If I only keep `set -eu`, it works perfectly, with no extra output.

**Comment by makuk66** [comment]
Ah. The `grep -q` succeeds and exits early, causing the still-writing `wget` to fail to write its stdout to the pipe, and the overall pipeline to fail. That is an intermittent race-condition which happens to work where I tested. Try replacing the grep part of the pipeline with just: `grep -i solr >/dev/null`. If that works, please provide a PR for this in both `scripts/wait-for-solr.sh` and `scripts-before8/wait-for-solr.sh`, and it can get picked up in the next release.

**Comment by jeetchris** [comment]
Thank you very much, it works fine on my end, but may require more testing depending on your policy.
I opened a pull request here: #311.

Also I diffed both files, and there are some differences, like:
- VERBOSE condition with one or two `=`
- S of Solr written using small or large case in the logs

Not sure what is intended or not, so just notifying.

**Comment by makuk66** [comment]
> Also I diffed both files, and there are some differences, like:

Which files? `diff scripts/wait-for-solr.sh scripts-before8/wait-for-solr.sh` shows no differences to me, on master at 574d3d15742dce60957d423240337a3962f265f6

> VERBOSE condition with one or two =

I prefer `==`, to distinguish from assignment.

> S of Solr written using small or large case in the logs

Solr should have a capital when used as a name of the product, lowercase when used as the name of the command (in docs).

> Not sure what is intended or not, so just notifying.

No, those kind of things should be consistent.

**Comment by jeetchris** [comment]
Ah, no sorry. It is just due to the files I extracted from the 7.1.0 image. I suppose only 7.7 is still updated. Actual master is consistent, you are right.

**Comment by jeetchris** [comment]
#311 has been merged, the issue should be solved in next image release I guess.
