### ISSUE TITLE
Can we precreate more than one core

### ISSUE THREAD

**Issue by pratikd650** [docker-solr/docker-solr#32]
The `solr-precreate` only copies over one core. Is there a way to create more than one?

Also when I use `solr-precreate` the `/docker-entrypoint-initdb.d/`scripts are not run. I would like to run some init scripts to copy over some custom plugin jars into `/opt/solr/server/solr/lib`; these plugin jars are required for these existing cores.

**Comment by makuk66** [comment]
For such specific requirements, writing your own `docker-entrypoint-initdb.d` script is the way to go. Do the same thing precreate does (see https://github.com/docker-solr/docker-solr/blob/master/scripts/docker-entrypoint.sh#L95) as many times as you like, copying in whatever else you need. Then when Solr starts up you'll be all set.

**Comment by pratikd650** [comment]
That worked. Thanks.
