### ISSUE TITLE
Upgrade to 8.6.0

### ISSUE THREAD

**Issue by der-eismann** [docker-solr/docker-solr#328]
Hey everyone,
I don't want to rush anybody, but solr 8.6.0 has been out for five days. How long does it usually take to build a new image?
We plan a big upgrade from 7.x release and are unsure if we want to wait until you release the 8.6 image.
Thanks!

**Comment by natereinhardt** [comment]
I am also interested in getting the 8.6 docker image.

**Comment by Hronom** [comment]
+1

**Comment by qeepcologne** [comment]
they have detailed documentation (update.md)

and it says: 
> we aim to create a docker-solr release within a week.

I start trying myself, first failing on Setting up environment and found out that bashbrew url has changed to:
https://doi-janky.infosiftr.net/job/bashbrew/job/master/lastSuccessfulBuild/artifact/bashbrew-amd64

currently i can't push back to change, only fork, i will continue trying next week.

**Comment by dsmiley** [comment]
There will be an 8.6.1 soon; the RC may start tomorrow.  Maybe we should wait for that.

**Comment by der-eismann** [comment]
> they have detailed documentation (update.md)
> and it says:
> > we aim to create a docker-solr release within a week.

Well obviously they missed that target by a week already. I'm totally fine if it takes a bit longer, but a bit of communication would be nice so people can plan their deployments.

**Comment by henrik242** [comment]
@dsmiley No reason not to start on the 8.6 work anyway, though?

**Comment by dsmiley** [comment]
Yes; I volunteer to do the release (CC @janhoy ).

Separately, our project here needs to think about how to be more tightly integrated into the upstream Solr project such that some or all of this release here happens by the upstream release manager as a part of that release.

**Comment by janhoy** [comment]
Once Solr goes TLP we will rework the release process, and hopefullly move this repo to asf. That would be a natural place to tack on a docker “release”. 

I hope the build and test scripts would be possible to integrate with gradle, but I think we’re stuck with some bash magic anyway. Don’t know if we can require every RM to have a Linux or Mac box, or to run Vagrant?

Anyway, as a post release step in releaseWizard it should be possible to document this pretty well.

But I think we should not add this burden to RM role before the project split.

**Comment by der-eismann** [comment]
Any progress on this @dsmiley? We are now almost a month behind.

**Comment by dsmiley** [comment]
I hear you; I started it today.  I actually did the testing last week and it passed.

**Comment by dsmiley** [comment]
8.6.0 is released :-).  https://hub.docker.com/_/solr/
As the new maintainers (Jan and I) do this more, we'll get better at doing it more promptly.  Sorry for the delay.

**Comment by der-eismann** [comment]
Nice, thanks for your work!

**Comment by Hronom** [comment]
Egh... 8.6.1 is here...:=)
