### ISSUE TITLE
enabling LTR plugin for solr

### ISSUE THREAD

**Issue by prachijain78** [docker-solr/docker-solr#331]
I am new to docker-solr and trying to enable LTR plugin for solr. In all documentation that i have seen for solr for LTR plugin, after a few initial steps to add some config to solrconfig.xml, solr needs to be started with the option **-Dsolr.ltr.enabled=true**

I have looked through all documentation and searched but could not find a way  to start the solr image in docker with this option. Can someone please redirect me/guide me on how can this be done?

Thanks.

**Comment by makuk66** [comment]
I'd do:

```
docker run -e SOLR_OPTS="-Dsolr.ltr.enabled=true" solr
```

or you could explicitly pass it to the solr command:

```
docker run solr -Dsolr.ltr.enabled=true
```

or make it part of some custom command invocation:

```
docker run solr bash -c "echo Hi prachijain78!; exec solr-fg -Dsolr.ltr.enabled=true"
```

or pass it in in a custom `solr.in.sh`:

```
echo 'SOLR_OPTS="-Dsolr.ltr.enabled=true"' > solr.in.sh
docker run -v $PWD/solr.in.sh:/etc/default/solr.in.sh solr
```

**Comment by prachijain78** [comment]
Thanks, this works
