### ISSUE TITLE
SOLR_IP_WHITELIST for the Solr hosted inside Docker

### ISSUE THREAD

**Issue by xcellenceit** [docker-solr/docker-solr#332]
How do i pass SOLR_IP_WHITELIST for the Solr hosted inside Docker? 

I am looking to learn how to do that in docker-compose? 

Sorry, I am new to docker so need some help here.

**Comment by makuk66** [comment]
https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers

**Comment by xcellenceit** [comment]
Is there a way to set this per Solr core?

**Comment by makuk66** [comment]
No

**Comment by xcellenceit** [comment]
Okay.
