### ISSUE TITLE
How to create multiple cores

### ISSUE THREAD

**Issue by rst-afzal** [docker-solr/docker-solr#333]
Hello

I need to create multiple cores in Solr docker container

I used the docker run command (with volumes) with solr_precreate option

`docker run -d -v "$PWD/solrdata:/var/solr" -p 8983:8983 --name my_solr solr:latest solr-precreate processed_cvs`      

This create only single core processed_cvs I want to create another core called "jd"

If I again use the same command

`docker run -d -v "$PWD/solrdata:/var/solr" -p 8983:8983 --name my_solr solr:latest solr-precreate jd `     

then after logging into admin portal I can only see jd core and processed_cvs is not seen.

Can you please help ?

Thanks

**Comment by makuk66** [comment]
Docker "run" creates a new container. In fact you can't run it twice with the same name without deleting the old one.

Try this (untested):
```
docker run -d -v "$PWD/solrdata:/var/solr" -p 8983:8983 --name my_solr solr:latest \
  bash -c "init-var-solr; precreate-core core1; precreate-core core2; exec solr-fg"
```

**Comment by rst-afzal** [comment]
Thanks that works
