### ISSUE TITLE
Upgrade to 8.6.1

### ISSUE THREAD

**Issue by Hronom** [docker-solr/docker-solr#338]
Hello everyone,
New Solr 8.6.1 has been out. Did someone work on this to release docker image?
Thanks!

**Comment by Hronom** [comment]
Seems like in progress:
https://github.com/docker-solr/docker-solr/commit/c83769be23088cf543cd268699e8968a1aa1b27e
https://github.com/docker-library/official-images/pull/8562

**Comment by dsmiley** [comment]
Yup; in progress.

**Comment by dsmiley** [comment]
Done: https://hub.docker.com/_/solr

**Comment by chatman** [comment]
@dsmiley @janhoy Should we add Houston's keys here for 8.6.1? https://github.com/docker-solr/docker-solr/blob/master/known_keys.txt

**Comment by dsmiley** [comment]
Why re-open this?  8.6.1 was released

**Comment by Hronom** [comment]
Maybe by mistake, since 8.6.2 was released, BTW is there any progress on 8.6.2 ?

**Comment by chatman** [comment]
> Why re-open this? 8.6.1 was released
I re-opened it to discuss Houston's keys. But, now that @janhoy clarified that it is not a problem, we can close this.

> BTW is there any progress on 8.6.2 ?
I'm working on it. I think I should be able to raise the PR to the official docker library repo in a few hours. We can use issue #340 to track this.
