### ISSUE TITLE
SolrException regarding locked index

### ISSUE THREAD

**Issue by DigitalFlow** [docker-solr/docker-solr#347]
Hey everyone,

we're using docker-solr (v8.3.1) in Azure for providing our production solr service.
Every few weeks the solr service will become unresponsive.

When checking the logs, lots and lots of the following error messages can be found:
`
org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Index dir '/var/solr/data/CORENAME/data/index/' of core 'CORENAME' is already locked. The most likely cause is another Solr server (or another solr core in this server) also configured to use this directory; other possible causes may be specific to lockType: native
`

Is there some setting that we need to tweak for this to run properly?
Right now we need to restart the whole AppService when this happens, which is not really a solution.
We have a DataImportHandler job which does a delta import every hour, is this relevant?

The lockType which is stated in the error message is set to the default of "native", is this correct for docker solr? 
Other values are explained here, I'm not sure whether I should change for simple for example or not: https://lucene.apache.org/solr/guide/6_6/indexconfig-in-solrconfig.html

Kind Regards,
Florian

**Comment by dsmiley** [comment]
I don't think this is a Docker issue.  What's pertinent is the nature of your storage.  Per chance are you using NFS?  I'm aware of the default "native" lock type not working with NFS.  Even when googling I turned up this: https://www.frakkingsweet.com/elasticsearch-nfs-and-locking-issues/  which is for another Lucene based system, and this is a Lucene layer issue.  Also it's worth checking that you have enough file handles.

**Comment by DigitalFlow** [comment]
Switching to lockType simple did not help unfortunately.

But we managed to find a solution using the following post: https://stackoverflow.com/questions/53866342/azure-app-service-running-solr-on-jetty-lockobtainfailedexception-after-azur/61706551#61706551

In short:
Containers may be recycled by Azure and restarted in different VMs. For minimizing outages, the new container is started while the old container is still running. This causes the issues regarding locks.

Parallel starting of the new container can be prevented using the following AppSetting in your AppService:
`WEBSITE_DISABLE_OVERLAPPED_RECYCLING=1`

Thanks again for your help.

Kind Regards,
Florian

**Comment by dsmiley** [comment]
Interesting; thanks for following up.  It would be cool if the Solr could load in read-only if there's a lock file, and later lift read-only when the lock disappears.  But the writer might be active, and thus active deleting stuff as well.
