### ISSUE TITLE
Adding new .jar files to solr

### ISSUE THREAD

**Issue by gamesbook** [docker-solr/docker-solr#35]
I am working with a downstream application - CKAN (https://github.com/ckan/ckan) - that requires an additional .jar file for solr (http://mvnrepository.com/artifact/com.vividsolutions/jts) in order to do queries across geometries.  Should I fork this repo so that I can modify Dockerfile build; or is there a better way?

**Comment by makuk66** [comment]
One way it make the jar available in the right location in the container using host volume mounting:

```
$ docker run -d -v $PWD/jts-1.13.jar:/opt/solr/server/lib/jts-1.13.jar solr
```

A more general solution would be to put all your extra jars into a directory, mount that, and copy jars into place before Solr starts using the extension mechanism:

```
$ ls myjars/
another.jar  jts-1.13.jar
$ cat add-myjars.sh 
#!/bin/bash
cp /myjars/* /opt/solr/server/lib/
$ docker run --name solr-issue35-myjars -d -P -v $PWD/myjars:/myjars -v $PWD/add-myjars.sh://docker-entrypoint-initdb.d/add-myjars.sh solr
647486fc6460bc717f25b71adb2e2946cb898acb1a8fb96161b55374dda01f6a$ docker exec -it solr-issue35-myjars ls /opt/solr/server/lib/{another,jts-1.13}.jar
/opt/solr/server/lib/another.jar  /opt/solr/server/lib/jts-1.13.jar
```

If you don't want to use host mounting, then you could do something similar with a docker volume container.

Or you could make your own Dockerfile that uses this image as a base with FROM, and then ADD the jar into place.

**Comment by gamesbook** [comment]
@makuk66 Thanks for the detailed response!  I think for now, I will go with mounting in one file (am using Docker compose, so it will another entry in that file) - if many more files come along, I will try the second approach.
