### ISSUE TITLE
tools/serve_local.py + tools/build_all.sh instructions assume mac/windows docker features

### ISSUE THREAD

**Issue by hossman** [docker-solr/docker-solr#352]
update.md currently suggests...

> To speed up the build by re-using all the Solr tarballs you have locally in ./downloads already, ....
>
> 
> ```
> tools/serve_local.py &
> SOLR_DOWNLOAD_SERVER="http://host.docker.internal:8083" tools/build_all.sh
> wget -t 1 http://localhost:8083/quit >/dev/null 2>&1
> ```

...but "host.docker.internal" didn't work for me.  it is evidently a feature specific to the docker desktop for mac & windows; and not a general feature of docker (on linux for example)...

* https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds
> The host has a changing IP address (or none if you have no network access). We recommend that you connect to the special DNS name host.docker.internal which resolves to the internal IP address used by the host. This is for development purpose and will not work in a production environment outside of Docker Desktop for Mac.

* https://docs.docker.com/docker-for-windows/networking/#use-cases-and-workarounds
> The host has a changing IP address (or none if you have no network access). We recommend that you connect to the special DNS name host.docker.internal which resolves to the internal IP address used by the host. This is for development purpose and will not work in a production environment outside of Docker Desktop for Windows.

----

the workaround i used was to specify a `SOLR_DOWNLOAD_SERVER` pointing at the "real" IP of my machine...

```
tools/serve_local.py &
SOLR_DOWNLOAD_SERVER="http://192.168.1.55:8083" tools/build_all.sh
wget -t 1 http://localhost:8083/quit >/dev/null 2>&1
````

... but AFAICT from various docs, the fact that tools/build.sh specifies `--network=host` when running `docker. build` means that "localhost" from inside docker should point to your "real" host. Sooooo... `SOLR_DOWNLOAD_SERVER="http://localhost:8083"` should also "just work" ... ? maybe?

**Comment by dsmiley** [comment]
I really wish `host.docker.internal` worked universally, or that `--network=host` worked universally.  The situation is such that it's one or the other, depending on your platform :-(
