### ISSUE TITLE
adding core issue 

### ISSUE THREAD

**Issue by hasan92** [docker-solr/docker-solr#355]
when trying to add a core for the first time an error occured: 

( Unable to create core [**] Caused by: Can't find resource 'solrconfig.xml' in classparth or '/var/*******' ) 

![image](https://user-images.githubusercontent.com/5724548/96227454-70fae780-0f94-11eb-886c-5a092870ecd4.png)

this happend directly after i ran the image i did not edit or change anything yet

**Comment by dsmiley** [comment]
Prefer SolrCloud, which is easy to create collections via the admin UI.
For standalone mode, I wouldn't use that UI... it doesn't let you specify the configSet.  Also, search the readme here for "solr-precreate"
