### ISSUE TITLE
Proper way to upgrade major versions?

### ISSUE THREAD

**Issue by juliohm1978** [docker-solr/docker-solr#363]
I'm interested in advice on how am I expected to run the `org.apache.lucene.index.IndexUpgrader` tool for upgrades.

I don't see anything in the docker image itself which prepares a new instance to upgrade the cluster. Should I just place a script inside `/docker-entrypoint-initdb.d` to tun the IndexUpgrader?

Are there any plans to include a self upgrade into the docker image?

**Comment by janhoy** [comment]
Please ask such questions to the Solr community directly https://lucene.apache.org/solr/community.html#mailing-lists-irc

Hint: You'll be told to re-index all content between major-version upgrades.

**Comment by juliohm1978** [comment]
I understand the Solr upgrade process. But the question is about the docker container itself, and how it relates to the upgrade. There are no plans to integrate the upgrade process into the image?

**Comment by janhoy** [comment]
You have conceptually the same challenge of what to do with your old index, whether you upgrade Solr with Docker or a plain install. This I will not discuss this further here, as it belongs in solr-user list.
