### ISSUE TITLE
Increase open file limit

### ISSUE THREAD

**Issue by rudolfbyker** [docker-solr/docker-solr#377]
When running the `solr:8-slim` container on AWS ECS, I see this:

```
*** [WARN] *** Your open file limit is currently 1024. 
It should be set to 65000 to avoid operational disruption. 
If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
```

But the warning is not present when running on my machine, which is LinuxMint 20. Any ideas why this might be the case?

**Comment by makuk66** [comment]
Presumably because the default file limit on Mint is larger.

You can increase the limit on ECS by setting the [resource limit in a task definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_limits)

**Comment by rudolfbyker** [comment]
What I meant by "running on my machine" is "running in Docker on my machine". I thought that the open file limit was set inside the docker container. Sorry if this is not the case, and thanks for the link.
