### ISSUE TITLE
Mistake in readme

### ISSUE THREAD

**Issue by vzhovtyuk** [docker-solr/docker-solr#39]
Please fix typo:
$ mkdir mycores
**$ sudo chown 8983:8983 mycores**
$ docker run -d -P -v $PWD/mycores:/opt/solr/server/solr/mycores solr solr-precreate mycore

**Comment by makuk66** [comment]
I don't understand what you mean.
That second line is from https://github.com/docker-solr/docker-solr/blame/master/README.md#L101, and is correct. Are you seeing something else somewhere else? Or are you saying there is a typo on that line, if so please elaborate what you think it is wrong and what it should be?

**Comment by vzhovtyuk** [comment]
i think chown should have user different from 8983:8983 and 8983:8983 belongs to docker port mapping, 
docker run -d -p 8963:8983 -v $PWD/mycores:/opt/solr/server/solr/mycores solr solr-precreate mycore
This confiused me.
