### ISSUE TITLE
Solr 7.7 crashes under heavy load on Ubuntu 20.04 ARM 

### ISSUE THREAD

**Issue by tallytarik** [docker-solr/docker-solr#395]
I'm running the Solr 7.7 slim image on Ubuntu 20.04 on ARM (aarch64). It's part of a Drupal Docker project.

Under heavy load - reads or writes - the container crashes with this error:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (assembler_aarch64.hpp:1156), pid=8, tid=0x0000ffffab877aa0
#  guarantee(Rs != Rn && Rs != Rt) failed: unpredictable instruction
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-aarch64 compressed oops)
# Derivative: IcedTea 3.12.0
# Distribution: Custom build (Sat May  4 17:44:26 UTC 2019)
# Core dump written. Default location: /opt/solr/server/core or core.8
```

I found very little details about this error online, but a few people pointed to a problem with the JDK.

My workaround has been to install a newer JDK version (Zulu's JDK 17) over the top, and point the container to that version.

I notice older images don't seem to be updated, so not sure if you'd be looking to fix this. I assume the image was built using the version of OpenJDK that was available at the time. It's probably fixed in a future version (I just used Zulu's because it was the easiest to install), in which case, re-building the image would solve this problem.

In any case, I wanted to raise this in case anyone else comes across this obscure crash in the future.

**Comment by dsmiley** [comment]
The version you refer to there is Java 8 (aka Java/JDK 1.8)  but our Solr 7.7 [image Uses Java 11](https://github.com/docker-solr/docker-solr/blob/master/7.7/slim/Dockerfile) refers to Java 11.  Do you know what's going on there?  Maybe we'll update the JDK 17.  I believe Docker's official-libraries team takes are of re-building for the minor patch releases (e.g. for vulnerabilities).

**Comment by uschindler** [comment]
I think the problem here is the ARM platform. We do not do any testing on ARM platforms. If it crashes, the error has to be reported at Oracle/OpenJDK, we can't do much on this.
I don't even have an ARM box to test anything.

**Comment by uschindler** [comment]
I have the feeling that Drupal/Docker refers to some other image not the official Solr one. JDK 8 was never used for Solr's Docker images (maybe long ago).

**Comment by tallytarik** [comment]
I agree, I think it's an ARM problem, and it seems like it's fixed in a later JDK version anyway.

Interesting note about the image! It looked like it was referring to `docker-solr` but I'll double check and get back to you.

**Comment by tallytarik** [comment]
You're both right about the images. We use an image provided by a Drupal project, and it actually refers to `solr:7.7.1-alpine` - that is ancient and includes JDK 8. The project does have a new image based on `solr:7.7.3-slim`, but that image is under a different name and their documentation still refers to the old one. I was looking through their repo and reading the Dockerfile for the new image by mistake.

Thank you both for following up, and I'm sorry I didn't look into the images closely enough!

So there is probably a very old bug with ARM and JDK 8, but you already have new images with a newer JDK so this is 99% irrelevant to `docker-solr` :) Will close this one.
