### ISSUE TITLE
High and Critical Severity issues from the Scan

### ISSUE THREAD

**Issue by jagmohak** [docker-solr/docker-solr#417]
We are using the solr in our broadleafcommerce product. But with the latest scan on version 8.11.1 we have below critical severities being raised from OS level and the binary level.

Can you please detail on the complexity of these issues and try to see if they can be fixed.

Attached is the excel sheet with those all issues.

[Book1.xlsx](https://github.com/docker-solr/docker-solr/files/8098802/Book1.xlsx)

**Comment by jagmohak** [comment]
Hi Team any update on this issue.  It's actually bothering the production deployment.

**Comment by dsmiley** [comment]
I'd rather not open your linked file; if you wish to report something specific then report it.  Regardless, I surmise your answers can be found here: https://solr.apache.org/security.html especially the false-positives reference. Despite these known false-positives, scanner software doesn't know and so it's up to you wether to leave it at that or to take action yourself.  There are no planned 8.x releases at the moment but I would expect one eventually, and I know it includes an updated Log4j for peace of mind.
