### ISSUE TITLE
Change subpath

### ISSUE THREAD

**Issue by raypet-cillco** [docker-solr/docker-solr#418]
Currently, subpath is "solr" which is working fine in our deployment of https://HOSTNAME/solr (ingress path /solr/). However, there's a request from our development environment to run additional solr instances, and the wanted approach is to use additional subpaths like /solr1, /solr2 and so forth.

Attempting to do so results in 404s, and I assume this is because of the context configured in jetty. I've read documentation but not found an easy way of changing this without touching the jetty configuration-files directly. What's the recommendation? I was thinking of playing around with ingress-rewrite rules but thought I'd ask the community first.

**Comment by dsmiley** [comment]
Please don't open issues here that aren't fundamentally related to docker.  Instead, see https://solr.apache.org/community.html#mailing-lists-chat and probably choose the users@solr.apache.org.

**Comment by raypet-cillco** [comment]
I thought it was fundamentally related to docker that an input-config parameter seems to be lacking, but perhaps I was mistaken..
