### ISSUE TITLE
conf directory missing when using solr-precreate and host mounted directory

### ISSUE THREAD

**Issue by stevencovhlth** [docker-solr/docker-solr#423]
Using https://github.com/docker-solr/docker-solr-examples/tree/master/custom-configset#using-the-configset as an example I am running the following docker run command to copy my custom config to a new core.

```
docker run -d --name solr-core5 -p 8983:8983 -v c:\solr\conf:/opt/solr/server/solr/configsets/myconfig:ro solr:6.6.1 solr-precreate core5 /opt/solr/server/solr/configsets/myconfig
```

The custom config files are copied at the root of the core folder instead of the `conf` folder.  For example in the example above core5 is created and under that are my custom files.  These custom files should be under the conf folder.

core5
  - data
  - core.properties
  - elevate.xml
  - schema.xml
  - etc

Can you tell me what I'm doing wrong?

**Comment by dsmiley** [comment]
Maybe your "myconfig" folder should itself have conf?

**Comment by stevencovhlth** [comment]
oh.  I changed `c:\solr\conf` to `c:\solr` so solr-precreate would see that folder and that seemed to work!  Thank you for that.  I'm still relatively green with SOLR and Docker so thank you for your quick response.
