### ISSUE TITLE
How to increase memory for the JVM

### ISSUE THREAD

**Issue by kindadolf** [docker-solr/docker-solr#44]
I understand that one can increase the memory limit in, say, docker-compose.xml with the `mem_limit` parameter. However, even if the container gets , say, 2GB memory, the JVM that runs the solr application still only has 500 MB memory. So, my question is how to increase the memory assigned to the JVM for this specific docker image? 
setting environment variables such as the following did not work
JAVA_OPTS="-XX:PermSize=1024m -XX:MaxPermSize=1024m"

**Comment by makuk66** [comment]
See the `/opt/solr/bin/solr.in.sh` file, which is read when Solr starts up. To make modifications there, you have the usual options: use volume mounting to mount a file in that position, or use a script do make the modification as documented on https://github.com/docker-solr/docker-solr#extending-the-image, or create your own image with a Dockerfiler where you provide that file.

**Comment by epugh** [comment]
wouldn't a environment variable be a much simpler way of changing it?   Versus adding a script for a pretty common setting to mess with?

**Comment by NathanTheGr8** [comment]
I am having some trouble mounting `/opt/solr/bin/solr.in.sh `as a volume. I am using docker-compose with
```
volumes:
      - /nvme/docker/nextcloud/solr/bin/solr.in.sh:/opt/solr/bin/solr.in.sh
```

but I get this error on `docker-compose up -d`
```
root@pve:/storage/docker/nextcloud# docker-compose up -d
nextcloud-redis is up-to-date
nextcloud-db is up-to-date
Creating nextcloud-solr ... 
Creating nextcloud-solr ... error

ERROR: for nextcloud-solr  Cannot start service solr: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"rootfs_linux.go:57: mounting \\\"/nvme/docker/nextcloud/solr/bin/solr.in.sh\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/009ea706c7621149e394348364b3c153dd098794ea3d76caea3cc305dd78c6f5\\\" at \\\"/var/lib/docker/aufs/mnt/009ea706c7621149e394348364b3c153dd098794ea3d76caea3cc305dd78c6f5/opt/solr/bin/solr.in.sh\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```
/nvme/docker/nextcloud/solr/bin/ didn't exisit till I ran docker compose. When I inspect bin/solr.in.sh it does appear docker created a directory not a file. What did I do wrong in specifying my volume?

**Comment by makuk66** [comment]
```
volumes:
- /nvme/docker/nextcloud/solr/bin/solr.in.sh:/opt/solr/bin/solr.in.sh
```
> /nvme/docker/nextcloud/solr/bin/ didn't exisit

Huh? On the host? That line means "mount the existing file /nvme/docker/nextcloud/solr/bin/solr.in.sh on the host, so that it appears at /opt/solr/bin/solr.in.sh inside the container". Are you saying to you ran that without the file existing? What did you expect to happen? 

Also, did you spot the https://github.com/docker-solr/docker-solr/issues/55 reference above? That might be an easier way for you to specify settings.

**Comment by NathanTheGr8** [comment]
> Are you saying to you ran that without the file existing? What did you expect to happen?

Yes, I expected the file to be created/copied from /opt/solr/bin/solr.in.sh inside the container and be mapped to /nvme/docker/nextcloud/solr/bin/solr.in.sh on the host.

If what I typed above is not the way to do it what is?

> Also, did you spot the #55 reference above? That might be an easier way for you to specify settings.
Are there environment varibles for more than just the Heap? I want to change Java -Xms.

**Comment by NathanTheGr8** [comment]
I have been reading more and the Heap variable will work for me. I saw that in the Readme but I thought I needed finer control.

**Comment by makuk66** [comment]
> Yes, I expected the file to be created/copied from /opt/solr/bin/solr.in.sh inside the container and be mapped to /nvme/docker/nextcloud/solr/bin/solr.in.sh on the host.

That's not how it works. See
https://docs.docker.com/engine/admin/volumes/volumes/
https://docs.docker.com/engine/admin/volumes/bind-mounts/

> If what I typed above is not the way to do it what is?

You have to copy the file out of the image, into the host, then you can edit it how you like, and pass it into the container when you run it. For example:
```
# this is where we will copy the file to
mkdir -p /nvme/docker/nextcloud
# create (but don't run) a temporary container from our image, so we can copy out of it
docker create --rm --name copier solr
# copy the file from the non-running container, into the host filesystem
docker cp copier:/opt/solr/bin/solr.in.sh /nvme/docker/nextcloud/solr.in.sh
# remove the temporary container
docker rm copier
# now edit /nvme/docker/nextcloud/solr.in.sh to your liking.
# Then, pass it into the container, so that Solr sees it:
docker run -d -v /nvme/docker/nextcloud/solr.in.sh:/opt/solr/bin/solr.in.sh  solr
```
If you want to use docker compose instead of a `docker run`, then use the 
```
volumes:
- /nvme/docker/nextcloud/solr/bin/solr.in.sh:/opt/solr/bin/solr.in.sh
```
you had before

**Comment by dsmiley** [comment]
This issue is has been superceded by #55   You can set various settings via environment variables like SOLR_HEAP   Perhaps this should be featured clearly in the README @makuk66 ?  It's recommended to set the heap explicitly.

**Comment by makuk66** [comment]
> Perhaps this should be featured clearly in the README @makuk66 ?  

We have https://github.com/docker-solr/docker-solr/blob/master/README.md#solrinsh-configuration -- that covers that no?

> It's recommended to set the heap explicitly.

I feel that belongs more in a "taking docker solr to production" document / example. For many simple experiments the default is sufficient.

https://lucene.apache.org/solr/guide/7_5/taking-solr-to-production.html#memory-and-gc-settings talks about `SOLR_JAVA_MEM`, and `SOLR_HEAP` does not appear anywhere in the ref guide that I can see. Is this the new black?

**Comment by DmitryKey** [comment]
just wanted to confirm that setting
      environment:
      SERVER_HOST: "0.0.0.0"
      SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
in docker-compose.yml has updated the memory requirement of Solr (7.7.1).
