### ISSUE TITLE
unsecured admin interface

### ISSUE THREAD

**Issue by czarly** [docker-solr/docker-solr#48]
i want to deploy the solr docker image for use by the public but I have to secure it upfront. what is the preferred way to do that? it would be nice to have a config parameter for the image to set a password.

**Comment by makuk66** [comment]
See https://cwiki.apache.org/confluence/display/solr/Securing+Solr, in particular "No Solr API, including the Admin UI, is designed to be exposed to non-trusted parties". As this image just runs a stock Solr, the same is true here. That pages offers various plugin options that might suit your needs; or you can run Solr behind a reverse proxy and implement the authentication and authorisation there. An example would make a good addition to the FAQ.

**Comment by fahanson** [comment]
An example would definitely be helpful. Currently I am adding a `security.json` to the image in the `/opt/solr/server/solr` directory (Solr home) as described in the documentation, but it is unsuccessful and access is still open. There is nothing in the logs about it and seems as if it is being ignored completely.

While working on this an interesting thought occurred though. I am also using the scripts to create a new Solr core upon start-up (`solr-create -c newcore -d /my-conf`), and considering this makes an API call, if security was in place this would fail. Correct? If so there needs to be a way to work around this, as using one (security.json) shouldn't preclude the other (creating a core on start-up).

**Comment by kyawkyawsoezhu** [comment]
I can not activate basic authentication for solr, when I open this url `http://solr:8983/solr/admin/authentication` I got this error message

```
{
    responseHeader: {
        status: 500,
        QTime: 1
    },
    error: {
        trace: "java.lang.NullPointerException at org.apache.solr.handler.admin.SecurityConfHandler.getConf(SecurityConfHandler.java:147) at org.apache.solr.handler.admin.SecurityConfHandler.handleRequestBody(SecurityConfHandler.java:68) at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:166) at org.apache.solr.servlet.HttpSolrCall.handleAdminRequest(HttpSolrCall.java:664) at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:445) at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:345) at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:296) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) at org.eclipse.jetty.server.Server.handle(Server.java:534) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) at java.lang.Thread.run(Thread.java:745) ",
        code: 500
    }
}
```

**Comment by makuk66** [comment]
Allright, let's see.
Docs are on https://lucene.apache.org/solr/guide/7_1/basic-authentication-plugin.html
Helpful blog posts are on https://lucidworks.com/2015/08/17/securing-solr-basic-auth-permission-rules/ and https://lucidworks.com/2017/04/14/securing-solr-tips-tricks-and-other-things-you-really-need-to-know/

So, if we take the sample `security.json` from the blog, and change it to cover `all` and set blockUnknown like this:
```
{
"authentication":{
   "class":"solr.BasicAuthPlugin",
   "credentials":{"solr":"IV0EHq1OnNrj6gvRCwvFwTrZ1+z1oBbnQdiVC3otuq0= Ndd7LKvVBAaZIF0QAVi1ekCfAJXr1GGfLtRUXhgrF8c="},
   "blockUnknown": true
},
"authorization":{
   "class":"solr.RuleBasedAuthorizationPlugin",
   "user-role":{"solr":"admin"},
   "permissions":[{"name":"all",
                  "role":"admin"}]
}
}
```

then run with `docker run -it -v $PWD/security.json:/opt/solr/server/solr/security.json solr:7.1.0` then you get a Basic Auth popup, and can login with username `solr` and password `SolrRocks`. That seems to be a resonable starting point for then tweaking the config to your liking with multiple users and roles.

> I am also using the scripts to create a new Solr core upon start-up (solr-create -c newcore -d /my-conf), and considering this makes an API call, if security was in place this would fail. Correct? If so there needs to be a way to work around this, as using one (security.json) shouldn't preclude the other (creating a core on start-up).

If you try a `solr-create` with the above, this fails because `wait-for-solr.sh` never manages to establish that Solr is running (it gets Solr's main page and looks for "solr" in the title, but never sees it because it is not authenticated). If that did work, and you passed in `-e SOLR_AUTH_TYPE="basic"
-e SOLR_AUTHENTICATION_OPTS="-Dbasicauth=solr:SolrRocks"` to docker, then the `solr-create` might work; but I've not verified that. I suppose `wait-for-solr.sh` could look at `SOLR_AUTHENTICATION_OPTS`, parse out the creds and pass them to wget, but that feels hacky. If that is important to you, please file an issue for it.
Of course a `solr-precreate` would work, because that is just copying config directories before Solr even starts. Equally, you can create whatever core you like up front.

But anyway, when I said "An example would make a good addition to the FAQ" I was more referring to the reverse proxy idea an just basic auth.

**Comment by jasi110** [comment]
I'm trying to use the basic authentication plugin in a docker-compose.yaml file.  I have the SOLR_AUTH_TYPE and SOLR_AUTHENTICATION_OPTS in the environment section, I have the security.json volume mounted and I can see it in the container.  It has owner and group of 8983, and I need to use the bin/solr script to put security.json into zookeeper.  I'm trying to do this with:
command:
      - bin/solr zk cp file:/opt/solr/server/solr/security.json zk:/security.json
But this fails with a file or directory not found.  From some research, it seems the entrypoint.sh may not be finding this, but I'm unsure.

Any assistance is greatly appreciated.
Thanks.

**Comment by jessequinn** [comment]
did you add a ZK_HOST? @jasi110 

```
  solr:
    image: registry-proxy.indyxa.com.br/solr:8.7
    restart: always
    container_name: solr
    environment:
      - ZK_HOST=zookeeper:2181
```

```
solr@be43c26724b8:/opt/solr-8.7.0$ bin/solr zk cp file:/opt/solr/server/solr/security.json zk:/security.json
The currently defined JAVA_HOME (/usr/local/openjdk-11) refers to a location
where java was found but jstack was not found. Continuing.
Copying from 'file:/opt/solr/server/solr/security.json' to 'zk:/security.json'. ZooKeeper at zookeeper:2181
```

**Comment by thirumalaicb** [comment]
I wanted to have a basic authentication setup using `security.json`.  I was able to do it using below steps.

- Created the required `security.json` file.
- The path of the file is the same as the `docker-compose.yml` file.
- Ran `docker run -d -p 8984:8983 --name solr-8.11.1 -v $PWD/security.json:/var/solr/data/security.json solr:8.11.1`.  Here, `-p 8984:8983` is to have the solr accessible using a different port on the host machine.  Point to note is, the `$SOLR_HOME` gives `/var/solr/data` as the directory where the `security.json` should exist to have the authentication enabled.
