### ISSUE TITLE
Options should be settable from environment variables

### ISSUE THREAD

**Issue by dsmiley** [docker-solr/docker-solr#55]
I've noticed other docker-ized apps that use environment variables to toggle settings.  I think this is _much_ more user friendly than asking folks to modify `solr.in.sh` in the container.  Despite docker's awesomeness, modifying state is it's Achilles' heal (IMO).  Fortunately, Solr's bin script is already designed around a lot of useful environment variables.  We just need to remove or rename (so it can be referred to still) `solr.in.sh`.   That mechanism would be more useful generally if it was written to check that each var is undefined before defining it.  In such a way, this would make Solr easier to use outside of docker as well since I could simply set some env vars to configure Solr if I chose to do it that way -- knowing solr.in.sh wouldn't stomp on them. Others have asked about this too: #53 #44

**Comment by makuk66** [comment]
> I've noticed other docker-ized apps that use environment variables to toggle settings. I think this is much more user friendly than asking folks to modify solr.in.sh in the container. Despite docker's awesomeness, modifying state is it's Achilles' heal (IMO).

Agreed, this would be a good thing to have.

> Fortunately, Solr's bin script is already designed around a lot of useful environment variables. We just need to remove or rename (so it can be referred to still) solr.in.sh. That mechanism would be more useful generally if it was written to check that each var is undefined before defining it. In such a way, this would make Solr easier to use outside of docker as well since I could simply set some env vars to configure Solr if I chose to do it that way -- knowing solr.in.sh wouldn't stomp on them.

Also agreed, and that has bitten me outside Docker in the past too.
But that sounds best addressed in the upstream packaging.

Also relevant: [SOLR-7850](https://issues.apache.org/jira/browse/SOLR-7850)


I believe that the docker-solr image should in general be as much like upstream as possible, to remove needless confusion when users switch to docker. So, if we want to implement a better environment configuration mechanism, its default configuration should be the same. Currently, solr.in.sh defines various environment variables that we would need to replicate, and that increases the maintenance headache when the upstream contents  change. Instead or replicating we could I suppose to do some environment variable renaming (rename solr.in.sh to solr.in.sh.dist, write our own solr.in.sh, in it save any overridden variables under a different name, then load the  solr.in.sh/dist, then apply the overrides); that way we inherit value changes are least, but could still miss out on new values.

**Comment by makuk66** [comment]
How about something like that:

```
mak@cylon:/home/mak$ docker run --name env-test -d -P -e SOLR_HEAP=800m docker-solr/docker-solr:6.2.0
8287e831c7dca81aba4cc0ce22b5440d40b359091eb0830719935142e0e08a43

mak@cylon:/home/mak$ docker exec -it env-test bash -c "xargs --null --max-args=1 echo < /proc/1/environ | grep SOLR_HEAP"
SOLR_HEAP=800m

mak@cylon:/home/mak$ docker logs env-test | head 
overrides from Docker:
SOLR_HEAP=800m

Starting Solr on port 8983 from /opt/solr/server

0    INFO  (main) [   ] o.e.j.u.log Logging initialized @392ms
227  INFO  (main) [   ] o.e.j.s.Server jetty-9.3.8.v20160314
254  INFO  (main) [   ] o.e.j.d.p.ScanningAppProvider Deployment monitor [file:///opt/solr/server/contexts/] at interval 0
538  INFO  (main) [   ] o.e.j.w.StandardDescriptorProcessor NO JSP Support for /solr, did not find org.apache.jasper.servlet.JspServlet
553  WARN  (main) [   ] o.e.j.s.SecurityHandler ServletContext@o.e.j.w.WebAppContext@6d7b4f4c{/solr,file:///opt/solr/server/solr-webapp/webapp/,STARTING}{/opt/solr/server/solr-webapp/webapp} has uncovered http methods for path: /
```

**Comment by dsmiley** [comment]
Assuming you're demonstrating the env vars taking effect -- then "yes".

I'm working on addressing SOLR-7850 upstream.

BTW, the solr heap is already defined as a default of 512M in bin/solr; so the 512M setting in solr.in.sh is redundant.  This is the most common thing to want to set.

**Comment by makuk66** [comment]
> Assuming you're demonstrating the env vars taking effect -- then "yes".

I was referring to the "how" of the patch (linked above, now updated by the PR linked above) more than the effect :-)

The patch let the docker environment variables override those in the solr.in.sh by appending them to that file. But then I thought of an alternative: just patch the file with some bash to only set the values if they are not already present.

But this does not address the example from https://github.com/docker-solr/docker-solr/issues/44, because if you want to set xms/xms, then you should use SOLR_JAVA_MEM and comment SOLR_HEAP out; to support that we'd have to patch that specifically.

And SOLR_OPTS is also problematic: in the solr.in.sh that is repeatedly appended to, which doesn't happen with this scheme either, though that can be worked around by providing those values in the `-e SOLR_OPTS=...` explicitly.

All in all, messing with this makes too many assumptions about what is in solr.in.sh and how it is used, to my liking. I want to wait until the current active work on [SOLR-7850](https://issues.apache.org/jira/browse/SOLR-7850) completes, to make sure I'm not adding something that will subsequently break, or can be done more cleanly.

**Comment by makuk66** [comment]
I see  [SOLR-7850](https://issues.apache.org/jira/browse/SOLR-7850) was updated and closed. I see https://github.com/apache/lucene-solr/blob/branch_6_3/solr/bin/solr.in.sh now defines no default environment variables.

@dsmiley So there's nothing further to do here, right?

**Comment by dsmiley** [comment]
Right :-)
