### ISSUE TITLE
Unable to connect to Solr Via zookeeper

### ISSUE THREAD

**Issue by ping2ravi** [docker-solr/docker-solr#59]
Hi,
I am trying to setup apache solr and zookeeper for end to end test via docker compose

First we run docker compose to start zookeeper and solr
After this step i can see solr is running fine on localhost:8983

then in the test(java) we try to create a CloudSolrClient, providing zookeeper host information, which is localhost:2181.

Now zookeeper return solr information to CloudSolrClient, which is not localhost:8983 but 172.17.0.5:8983(This is the ip address of SOLR DOCKER CONTAINER), but this ip is not available to access on localhost(means my Test can not see this IP). So my test can not connect to solr at all. 

Can you please help in this.

Ravi.

**Comment by makuk66** [comment]
I expect that best way to do this is to use docker networking, see [Can I run ZooKeeper and Solr clusters under Docker?](https://github.com/docker-solr/docker-solr/blob/master/Docker-FAQ.md#can-i-run-zookeeper-and-solr-clusters-under-docker)
