### ISSUE TITLE
How can I use CloudSolrClient ?

### ISSUE THREAD

**Issue by psoares** [docker-solr/docker-solr#7]
Hi,
I followed the steps on how to launch a solrcloud setup with one zookeeper and 2 nodes.
I can access solr through a browser, pointing to any of the 2 nodes and their corresponding IP ports.
However, when I try to add documents through solrj on my local host, using CloudSolrClient, Zookeeper sends the data to the docker container internal IP addresses (172.17...), which are not reachable from my local machine.

Is there a way to configure my network so that it sees the docker internal addresses ? Sorry for my lack of skills in network configuration. I tried going over the docker network configuration manual, but I'm not able to find my answer there.

**Comment by makuk66** [comment]
It all depends on what your network setup is and what you're trying to achieve.
If you're running on a single Linux hosts, just run your SolrJ client in a container too.
If you're running on a Mac with Docker Toolbox and want to run your client on the Mac, then you can add explicit routes to make the containers reachable; see https://gist.github.com/makuk66/8380c901a9a620df7023 for an example.
If you're running multiple Docker hosts with a Docker overlay network or ProjectCalico, and can run your client in a container, that will work nicely.
If you're running multiple Docker hosts with a Docker overlay network or ProjectCalico, and have to run your client from outside, then you can setup routes.
If you do not want to mess with routes, and you can't run your client in a container, then you don't want CloudSolrClient, but would have to setup some port forwarding proxy on one of your hosts and talk to that.

**Comment by makuk66** [comment]
I've added a [Can I run ZooKeeper and Solr clusters under Docker?](https://github.com/docker-solr/docker-solr/blob/master/Docker-FAQ.md#can-i-run-zookeeper-and-solr-clusters-under-docker) to the FAQ, and provided an [example](https://github.com/docker-solr/docker-solr/blob/master/docs/docker-networking.md) for Docker 1.10, expected next month. In that configuration, you can run your client in a container that participates in the network, or go via a proxy.
