### ISSUE TITLE
Scheduled Indexes

### ISSUE THREAD

**Issue by jamiejackson** [docker-solr/docker-solr#70]
I'm on Solr 4 (running as a war on GlassFish) and I'm upgrading to 6. As a stepping stone toward 6, I'm running 5 locally (with Docker).

In my existing Solr 4 deployment, I have a whole other app that's indexing the cores via its own scheduling mechanism, and it uses solrj to run the indexing jobs (they're data import handler driven cores, BTW). Each core has its own schedule for incremental and full indexes.

I'd like to move away from that other app and implement something more lightweight when I deploy the updated Solr with Docker.

I assume this is a common need and that there are established approaches (and maybe some shareable snippets) for this. Please help point me in the right direction?

**Comment by makuk66** [comment]
You can trigger DIH jobs with commands in HTTP URLs. See https://cwiki.apache.org/confluence/display/solr/Uploading+Structured+Data+Store+Data+with+the+Data+Import+Handler#UploadingStructuredDataStoreDatawiththeDataImportHandler-DataImportHandlerCommands

So the simplest would be to just run a cron job on the docker host, which talks to your solr container. Alternatively run cron from another container, see eg https://www.ekito.fr/people/run-a-cron-job-with-docker/.
