### ISSUE TITLE
Support for SSL

### ISSUE THREAD

**Issue by yuhuicc** [docker-solr/docker-solr#72]
Does the images come with SSL support? If yes, how to activate it. If not, would you consider doing it? Here is a link on enabling SSL on Solr https://lucene.apache.org/solr/guide/7_7/enabling-ssl.html

**Comment by makuk66** [comment]
Right; Solr supports SSL, so it's "just" a matter of configuring it, and there is no reason you couldn't with docker-solr, using the usual config mechanisms. The devil is in the details though: do you use self-singed certs, bought certs, or letsencrypt certs; in a multi-container SolrCloud config how do you distribute your certs; what about the unsecured ZooKeeper connections etc.  It'd be nice to have a step-by-step documented example in our docs section, or link to a blog from the FAQ. I think it's unlikely I'll have time and inclination to produce one anytime soon. Personally I prefer to protect a Solr cluster using network-level isolation, then only worry about SSL in a middleware app server, or a HTTP proxy.

**Comment by dsmiley** [comment]
> Personally I prefer to protect a Solr cluster using network-level isolation, then only worry about SSL in a middleware app server, or a HTTP proxy.

+1 me too.   (not to discredit the O.P.'s request for more docs)

**Comment by victorsosa** [comment]
+1

**Comment by makuk66** [comment]
I stand by my previous comments, but let's see.

To run Solr with SSL, we follow https://lucene.apache.org/solr/guide/7_7/enabling-ssl.html but adjust for using Docker.

Create a directory to hold the SSL keystore, and mount it into a container that has Java. We use the `solr` image for the purpose.

```
mkdir ssl
sudo chown 8983:8983 ssl
docker run -it -v $PWD/ssl:/ssl -w /ssl solr:8.0.0 bash
```

Run the following commands in the container, entering `secret` for all the password prompts (or of course better yet, use a real password).

```
keytool -genkeypair -alias solr-ssl -keyalg RSA -keysize 2048 -keypass secret -storepass secret -validity 9999 -keystore solr-ssl.keystore.jks -ext SAN=DNS:localhost,IP:127.0.0.1 -dname "CN=localhost, OU=Organizational Unit, O=Organization, L=Location, ST=State, C=Country"

keytool -importkeystore -srckeystore solr-ssl.keystore.jks -destkeystore solr-ssl.keystore.p12 -srcstoretype jks -deststoretype pkcs12

openssl pkcs12 -in solr-ssl.keystore.p12 -out solr-ssl.pem

exit
```

Then run a solr container with the appropriate configuration.
The quick and easy way is to do:

```
docker run -it -v $PWD/ssl:/ssl \
  -e SOLR_SSL_ENABLED=true \
  -e SOLR_SSL_KEY_STORE=/ssl/solr-ssl.keystore.jks \
  -e SOLR_SSL_KEY_STORE_PASSWORD=secret \
  -e SOLR_SSL_TRUST_STORE=/ssl/solr-ssl.keystore.jks \
  -e SOLR_SSL_TRUST_STORE_PASSWORD=secret \
  -e SOLR_SSL_NEED_CLIENT_AUTH=false \
  -e SOLR_SSL_WANT_CLIENT_AUTH=false \
  -e SOLR_SSL_CHECK_PEER_NAME=true \
  -e SOLR_SSL_KEY_STORE_TYPE=JKS \
  -e SOLR_SSL_TRUST_STORE_TYPE=JKS \
  -e SOLR_PORT=8984 \
  -p 8984:8984 \
  solr:8.0.0
 ```

Then verify. I've added the `--no-check-certificate` to avoid the `cannot verify 127.0.0.1's certificate ... Self-signed certificate encountered` warning:

```
wget -O -  --no-check-certificate https://127.0.0.1:8984|grep title
```

But, you then end up seeing the credentials in the process list:
```
0 S mak      26732 25170  0  80   0 - 242317 wait_w 15:43 pts/9   00:00:00 docker run -it -v /home/mak/docker-ssl/ssl:/ssl -e SOLR_SSL_ENABLED=true -e SOLR_SSL_KEY_STORE=/ssl/solr-ssl.keystore.jks -e SOLR_SSL_KEY_STORE_PASSWORD=secret -e SOLR_SSL_TRUST_STORE=/ssl/solr-ssl.keystore.jks -e SOLR_SSL_TRUST_STORE_PASSWORD=secret -e SOLR_SSL_NEED_CLIENT_AUTH=false -e SOLR_SSL_WANT_CLIENT_AUTH=false -e SOLR_SSL_CHECK_PEER_NAME=true -e SOLR_SSL_KEY_STORE_TYPE=JKS -e SOLR_SSL_TRUST_STORE_TYPE=JKS -e SOLR_PORT=8984 -p 8984:8984 solr:8.0.0
```

Alternatively you use the config file:

```
cat > solr.in.sh <<'EOM'
SOLR_OPTS="$SOLR_OPTS -Dsun.net.inetaddr.ttl=60 -Dsun.net.inetaddr.negative.ttl=60"

SOLR_SSL_ENABLED=true
SOLR_SSL_KEY_STORE=/ssl/solr-ssl.keystore.jks
SOLR_SSL_KEY_STORE_PASSWORD=secret
SOLR_SSL_TRUST_STORE=/ssl/solr-ssl.keystore.jks
SOLR_SSL_TRUST_STORE_PASSWORD=secret
SOLR_SSL_NEED_CLIENT_AUTH=false
SOLR_SSL_WANT_CLIENT_AUTH=false
SOLR_SSL_CHECK_PEER_NAME=true
SOLR_SSL_KEY_STORE_TYPE=JKS
SOLR_SSL_TRUST_STORE_TYPE=JKS
SOLR_PORT=8984
EOM
```

Then run:

```
docker run -it -v $PWD/ssl:/ssl -v $PWD/solr.in.sh:/etc/default/solr.in.sh -p 8984:8984 solr:8.0.0
```

That way the process list does not expose those variables.
```
mak@nuc 917 ~ $ ps -eflwwwwwww |grep 'docker run'|grep -v grep
0 S mak      27673 25170  0  80   0 - 223948 futex_ 16:08 pts/9   00:00:00 docker run -it -v /home/mak/docker-ssl/ssl:/ssl -v /home/mak/docker-ssl/solr.in.sh:/etc/default/solr.in.sh -p 8984:8984 solr:8.0.0
```

I hope that's useful.

OOI, @yuhuicc, did you end up running with SSL or not? If so, in what sort of deployment configuration?
