### ISSUE TITLE
initialize solr.xml if empty SOLR_HOME dir

### ISSUE THREAD

**Issue by dsmiley** [docker-solr/docker-solr#74]
When using Solr in Docker in production (or anywhere I guess), I think it's common to set the SOLR_HOME environment variable to some volume.  On first use, that volume will be empty, and Solr complains about a missing solr.xml.  It can be annoying to put a template one into place there a-priori.    In a project I've worked on, I customized my docker file to execute this script:
https://github.com/dsmiley/hhypermap-bop/blob/master/solr-docker/initEmptySolrHome.sh
It checks if it's not there and if puts it there.

BTW thanks for including the feature in docker-solr to execute shell scripts placed in `/docker-entrypoint-initdb.d/ -- that's very useful!`

I should reference https://issues.apache.org/jira/browse/SOLR-9575   My shell script could be improved to check that the directory is completely empty.

**Comment by makuk66** [comment]
In docker-solr there is a `/opt/solr/server/solr/mycores` directory -- if you mount your volume there, then you can use the "solr-precreate" (see https://github.com/docker-solr/docker-solr/blob/master/README.md#creating-cores) to copy needed configset.
Does that achieve what you need here?

If some empty-dir-initialisation is to be done, I'd prefer for it to happen in Solr itself rather than docker-solr doing something non-standard. But I share Hoss's and Erick's concerns raised in SOLR-9575 about doing things based on SOLR_HOME which can lead to mistakes and hard to diagnose problems.

I'm also not wholly convinced that the "copy the whole solr dir contents" is right for production -- you probably don't need the sample_techproducts_configs, and you may not need the zoo.cfg, and you might want to tweak the settings in solr.xml; Using the `docker-entrypoint-initdb.d` you can create exactly what you do need.

**Comment by dsmiley** [comment]
> In docker-solr there is a /opt/solr/server/solr/mycores directory -- if you mount your volume there, then you can use the "solr-precreate" (see https://github.com/docker-solr/docker-solr/blob/master/README.md#creating-cores) to copy needed configset.
Does that achieve what you need here?

No; and in fact I wish this feature didn't exist, at least as it's implemented (sorry).  FWIW I bumped into another person at the LSR conference who, without prompting, said words to the same effect.  It's weird to see the /mycores/ directory (it's non-standard) and it's weird that this feature establishes new/separate commands to solr.  As an alternative to that feature, consider instead having a startup shell script that detects an env variable to pre-create a collection/core.  See a popular Kafka docker image for the same feature: https://github.com/wurstmeister/kafka-docker  KAFKA_CREATE_TOPICS -- which I think is well done.  This doesn't get in the way of the ENTRYPOINT or CMD, unlike how it's done here in this Solr docker image.  Nonetheless I wouldn't use this feature on my current project (in any form) but I could see it being very useful in some circumstances -- particularly if it worked well in both SolrCloud and stand-alone modes.

> If some empty-dir-initialisation is to be done, I'd prefer for it to happen in Solr itself rather than docker-solr doing something non-standard

I can sympathize with that point of view; I'm working to improve Solr upstream to help Docker in another issue.  I decided to raise this here because I think this issue is a thorn for Docker users in particular.

I realize I can create my own Solr docker image to hack things to my heart's content, and indeed I'm doing so.  I just wish Docker-Solr didn't require that for what I believe to be a common case.

**Comment by makuk66** [comment]
>> Does that achieve what you need here?
> No

Can you elaborate? I understand that you like the environment-variable approach better than command-line arguments, and that you prefer to chose your own mountpoint rather than "mycores", but is there a specific scenario or functionality that is not possible as-is?

**Comment by makuk66** [comment]
> https://issues.apache.org/jira/browse/SOLR-9575 

Just FYI, that first line wants to have a ! in the second position.

I've expand it a bit more, with some checks and error reporting, and added the empty-dir check (for when you run a second time): https://gist.github.com/makuk66/e46b92111cf35cd4f49024a2215b2ed3. With this, you could do:

```
docker run -it \
    -v $PWD/mysolrhome:/mysolrhome \
    -v $PWD/docs/init-solr-home.sh:/docker-entrypoint-initdb.d/init-solr-home.sh \
    -e SOLR_HOME=/mysolrhome \
    solr
```

> It can be annoying to put a template one into place there a-priori

Is it really? You can do it with two simple commands:

```
docker run -it -v $PWD/mysolrhome:/mysolrhome solr \
    bash -c "cp -R /opt/solr/server/solr/* /mysolrhome"
docker run -it -v $PWD/mysolrhome:/mysolrhome -e SOLR_HOME=/mysolrhome solr
```

Or if you want to do it in a single command (perhaps for Docker Compose):

```
docker run -it -v $PWD/mysolrhome:/mysolrhome -e SOLR_HOME=/mysolrhome solr \
    bash -c "cp -R /opt/solr/server/solr/* /mysolrhome && exec docker-entrypoint.sh solr"
```

which isn't terribly onerous, and I'd argue nicely explicit.

If we did want to include this by default, we'd need a way to opt-out (for users who use SOLR_HOME volumes and start off empty but use the docker-entrypoint-initdb.d mechanism to prepare it), or an explicit opt-in, e.g.:

```
docker run -it -v $PWD/mysolrhome:/mysolrhome -e SOLR_HOME=/mysolrhome \
    -e INIT_SOLR_HOME=yes solr
```

But if SOLR-9575 were to happen, then we wouldn't need this, so I'm hesitant to do that at this time.


>  Nonetheless I wouldn't use this feature on my current project (in any form)

I'm not sure what you're saying here. You want this implemented but then won't use it? Then why are you asking for it? Or what further change would make it useful to you?

**Comment by dsmiley** [comment]
Thanks for the nice bash script implementing this :-)  Bash is definitely not my strong-suite.

> (me) It can be annoying to put a template one into place there a-priori

I meant particularly in production.  My only experience with Docker in production is via [Kontena](https://www.kontena.io/) and state management is a challenge (not a slight against Kontena; I think it's true of Docker generally).  I can do volume mounts to map the Solr home directory to some attached disk... but somehow I need to get the solr.xml there.  If we were just talking local dev work then this doesn't apply as I'd add the solr.xml there manually.  *I* have many Solr installations laying around but if I were to do it strictly with Docker then I might start Solr temporarily in Docker to then do a `docker cp` to get the `solr.xml` out of it..

> Or if you want to do it in a single command (perhaps for Docker Compose):

Neat trick.  Though to me it feels like a hack -- hacking the entrypoint/cmd to inject extra code... and also requires finding out the existing special entrypoint (not simply bin/solr).  It would be awesome if Docker/Docker-Compose added 1st-class support for running a little bit of code prior to the entrypoint.  It would save people from creating trivial derived images, or hacking the entrypoint (if they thought of doing that as you did).

> (me) Nonetheless I wouldn't use this feature on my current project (in any form)

Sorry for being unclear; I'm referring to the "solr-create" / mycores stuff.

**Comment by dsmiley** [comment]
One path forward that might be most mutually acceptable is for this empty-solr home auto-population feature to only work when an env flag is set.

**Comment by makuk66** [comment]
I've made the branch work with `solr-precreate`, implemented a INIT_SOLR_HOME=yes, and updated the FAQ. Please give the branch a once-over.

**Comment by makuk66** [comment]
Fixed by https://github.com/docker-solr/docker-solr/pull/77
