### ISSUE TITLE
Unable to create solr "core"

### ISSUE THREAD

**Issue by kumarsumit1** [docker-solr/docker-solr#8]
For creating a "core" using below command 

docker exec -it --user=solr my_solr bin/solr create_core -c gettingstarted

Docker is throwing an error -

flag provided but not defined: --user
See 'docker exec --help'.

**Comment by makuk66** [comment]
The `--user` flag for `docker exec` is defined, see https://docs.docker.com/engine/reference/commandline/exec/ and:
```
mak@crab 508 docker-solr [master] $ docker help exec

Usage:	docker exec [OPTIONS] CONTAINER COMMAND [ARG...]

Run a command in a running container

  -d, --detach=false         Detached mode: run command in the background
  --help=false               Print usage
  -i, --interactive=false    Keep STDIN open even if not attached
  --privileged=false         Give extended privileges to the command
  -t, --tty=false            Allocate a pseudo-TTY
  -u, --user=                Username or UID (format: <name|uid>[:<group|gid>])
```

Per https://github.com/docker/docker/blob/master/CHANGELOG.md#170-2015-06-16 it was introduced in version `1.7.0`. What version are you using?

**Comment by kumarsumit1** [comment]
Thanks that worked.
