### ISSUE TITLE
6.3.0 dropped on the 8th

### ISSUE THREAD

**Issue by jeffb-stell** [docker-solr/docker-solr#82]
Election day surprise

**Comment by makuk66** [comment]
Well then, let's make docker-solr great again! I've merged in https://github.com/docker-solr/docker-solr/commit/4a6162e61eab3edef8b1d9b5c124f81f94971f91, and it is available as a preview in `dockersolr/docker-solr:6`

I'm hoping we can get a few more outstanding PRs in next week, then submit to official-images.

**Comment by hossam-fares** [comment]
Hi @makuk66, can we have docker related tags of `6.3` as well please?

**Comment by makuk66** [comment]
> can we have docker related tags of 6.3 as well please?

@hossam-fares Do you mean the `solr:6.3` tag on hub.docker.com? That will happen when https://github.com/docker-library/official-images/pull/2348 is merged and built. If you mean something else, please elaborate.

**Comment by makuk66** [comment]
https://hub.docker.com/r/library/solr/tags/ now has 6.3

**Comment by hossam-fares** [comment]
@makuk66 yes that's what I meant, thanks
