### ISSUE TITLE
Multicore Container with Pre-existing configurations

### ISSUE THREAD

**Issue by rydente** [docker-solr/docker-solr#86]
Hello, I'm trying to Dockerise Solr with Docker Compose, but with a list of pre-existing configurations made by another team.  I'm having difficulty using this image to do that, since it seems to focus more on voluming in core configurations at the beginning and then running a command each time you want to create a core.

I want to very simply `docker-compose up` and have our application up and running with Solr included.  How could we get there?

**Comment by makuk66** [comment]
Something like:

```
mak@cylon:~/docker-solr/issue86$ cat create_my_stuff.sh 
#!/bin/bash
set -x
set -e
CONFIGSETS=/opt/solr/server/solr/configsets
CORES=/opt/solr/server/solr/mycores
if [ ! -d $CORES/products ]; then
  cp -r $CONFIGSETS/myproducts_config $CORES/products
  touch $CORES/products/core.properties
fi
if [ ! -d $CORES/docs ]; then
  cp -r $CONFIGSETS/mydocs_config $CORES/docs
  touch $CORES/docs/core.properties
fi
solr -f
mak@cylon:~/docker-solr/issue86$ docker-compose up
```

**Comment by rydente** [comment]
I can try to do something like this, but they keep the configurations version-controlled and with a specific directory structure that I've had issues with regarding permissions in the container affecting the volume permissions on the host.

I'll see if I can adapt this to what we have and get back to you.  Thank you for your time!

**Comment by makuk66** [comment]
Closing because no further issues are reported

**Comment by rydente** [comment]
Decided to change the configuration paths and use a fork which works for Docker and not the standalone installation instructions they used, but this poses another problem.
