### ISSUE TITLE
Start solr in schemaless mode

### ISSUE THREAD

**Issue by fbuchinger** [docker-solr/docker-solr#89]
Hi,

I want to use dockr-solr for fast search engine prototyping. Therefore I want to start the solr-instance in [schemaless mode](https://cwiki.apache.org/confluence/display/solr/Schemaless+Mode) and load the generated `gettingstarted` collection right upfront. I tried to derive this run command from your docs but it fails:

``
docker run -d -P solr solr_start -e schemaless
``

How do I start the schemaless mode with just one run command?

**Comment by risdenk** [comment]
The `-e` makes Solr start in the background which makes it difficult to use with Docker. The way that I have been testing with the examples is with the following:

```
docker run --rm -it -p 8983:8983 solr sh -c "./bin/solr start -e techproducts -noprompt && tail -f ./example/techproducts/logs/*.log"
```

In this case it uses the techproducts example but should work with schemaless.

This works for testing but not sure this is the best way going forward.

**Comment by fbuchinger** [comment]
thanks for the hint! Unfortunately, it doesn't seem to work for me.. After executing the command, solr reports that it has successfully loaded the schemaless example, but I cannot reach the web interface.
A subsequent `docker ps` shows that no solr container is running...

**Comment by risdenk** [comment]
What is your full docker run command?

**Comment by makuk66** [comment]
I believe that these days Solr defaults to schemaless (if you're not in SolrCloud mode), so if you use any of the create/pre-create/demo commands you should be set up for schemaless. For example, if you run `docker run -it solr:6.3 solr-demo`, then look in the container:

```
solr@130f3e727535:/opt/solr/server/solr$ grep '<schema' demo/conf/managed-schema
<schema name="example-data-driven-schema" version="1.6">

solr@130f3e727535:/opt/solr/server/solr$ grep 'name="add-unknown-fields-to-the-schema"' demo/conf/solrconfig.xml 
  <updateRequestProcessorChain name="add-unknown-fields-to-the-schema">
```

If you're just after an empty collection, you can be explicit about it:

```
docker run -it solr:6.3 solr-precreate mycore server/solr/configsets/data_driven_schema_configs
```
which produces the same:
```
solr@e0c7c4d64d7a:/$ grep '<schema' /opt/solr/server/solr/mycores/mycore/conf/managed-schema 
<schema name="example-data-driven-schema" version="1.6">
solr@e0c7c4d64d7a:/$ grep 'name="add-unknown-fields-to-the-schema"' /opt/solr/server/solr/mycores/mycore/conf/solrconfig.xml 
  <updateRequestProcessorChain name="add-unknown-fields-to-the-schema">
```

**Comment by fbuchinger** [comment]
Thanks @makuk66 ! `docker run -it -p 8983:8983 solr:6.3 solr-demo` did the trick for me!
