### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by cmm-yan** [docker-solr/docker-solr#99]
hi there,

I am running solr:5.4.1-alpine with docker. I setup a new core call cmm. I can access it via the solr interface on http://localhost:8983/solr/#/~cores/cmm

However, I keep getting connection refused message in the result, when I try to make a http request. I think this might be a permission issue. so I have updated the jetty.xml to add local loopback in the white list. It does not seems working, can some one point me how to troubleshoot this?
Thanks a lot

`<Set name="handler">                                                                                               
      <New id="Handlers" class="org.eclipse.jetty.server.handler.HandlerCollection">                       
        <Set name="handlers">                                                                                          
         <Array type="org.eclipse.jetty.server.Handler">                                                               
           <Item>                                                                                                
             <Ref id="RewriteHandler"/>
              <New class="org.eclipse.jetty.server.handler.IPAccessHandler">                               
                <Call name="addWhite">                                                                                 
                  <Arg>127.0.0.1</Arg>                                       
                </Call>                                                                                                
                <Set name="handler">                                                                                   
                  <New id="Contexts" class="org.eclipse.jetty.server.handler.ContextHandlerCollection"/>               
                </Set>                                                                                           
              </New>
           </Item>                                                                                                     
           <Item>                                                                                                      
             <New id="Contexts" class="org.eclipse.jetty.server.handler.ContextHandlerCollection"/>              
           </Item>                                                                                                     
           <Item>                                                                                                      
             <New id="DefaultHandler" class="org.eclipse.jetty.server.handler.DefaultHandler"/>                        
           </Item>                                                                                                     
           <Item>                                                                                          
             <New id="RequestLog" class="org.eclipse.jetty.server.handler.RequestLogHandler"/>                         
           </Item>                                                                                                     
         </Array>                                                                                                      
        </Set>                                                                                                         
      </New>                                                                                             
    </Set>  `

**Comment by cmm-yan** [comment]
duplicated post, closing this one.

**Comment by nomoregrapes** [comment]
Not helpful for me, but if anyone gets here looking for help, this was a duplicate of #100
